测速日志 2025-09-29 09:42:48
[2025-09-29 09:42:51] ✅ 测速成功: http://61.221.215.25:8800/hls/43/index.m3u8
   速度: 236.33KB/s | 数据量: 0.2KB | 总耗时: 0.28s
[2025-09-29 09:42:51] ✅ 测速成功: http://8.138.7.223/tv/cctv7.m3u8
   速度: 132.81KB/s | 数据量: 0.1KB | 总耗时: 0.37s
[2025-09-29 09:42:51] ✅ 测速成功: http://8.138.7.223/【公众号：榴芒电视】/cctv7.m3u8
   速度: 209.96KB/s | 数据量: 0.2KB | 总耗时: 0.38s
[2025-09-29 09:42:51] ✅ 测速成功: http://123.146.162.24:8017/c2F0hmi/1000/live.m3u8
   速度: 438.48KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:42:51] ✅ 测速成功: http://61.162.52.6:8088/newlive/live/hls/60/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.40s
[2025-09-29 09:42:51] ✅ 测速成功: http://123.146.162.24:8013/tslslive/PU2vzMI/hls/live_sd.m3u8?zzhongqd
   速度: 545.90KB/s | 数据量: 0.5KB | 总耗时: 0.41s
[2025-09-29 09:42:51] ✅ 测速成功: http://120.198.95.220:9901/tsfile/live/1038_1.m3u8?key=txiptv
   速度: 658.20KB/s | 数据量: 0.7KB | 总耗时: 0.42s
[2025-09-29 09:42:51] ✅ 测速成功: http://8.138.7.223/【公众号：榴芒电视】/农林卫视.m3u8
   速度: 118.16KB/s | 数据量: 0.1KB | 总耗时: 0.39s
[2025-09-29 09:42:51] ✅ 测速成功: http://112.27.235.94:8000/hls/25/index.m3u8
   速度: 240.23KB/s | 数据量: 0.2KB | 总耗时: 0.32s
[2025-09-29 09:42:51] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/33/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.76s
[2025-09-29 09:42:51] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/24/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.78s
[2025-09-29 09:42:51] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/45/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.78s
[2025-09-29 09:42:51] ✅ 测速成功: http://8.138.7.223/tv/gzjs.m3u8
   速度: 133.79KB/s | 数据量: 0.1KB | 总耗时: 0.36s
[2025-09-29 09:42:51] ✅ 测速成功: http://123.146.162.24:8013/tslslive/noEX9SG/hls/live_sd.m3u8?zzhongqd
   速度: 545.90KB/s | 数据量: 0.5KB | 总耗时: 0.41s
[2025-09-29 09:42:51] ✅ 测速成功: http://203.205.191.53/yun-live.jxtvcn.com.cn/live-jxtv/tv_jxtv1.m3u8
   速度: 291.99KB/s | 数据量: 0.3KB | 总耗时: 0.16s
[2025-09-29 09:42:52] ✅ 测速成功: http://222.128.55.152:9080/live/dwq.m3u8
   速度: 0.43KB/s | 数据量: 0.1KB | 总耗时: 0.61s
[2025-09-29 09:42:52] ✅ 测速成功: http://111.202.12.159:8080/kYGHWzA/1000/live.m3u8
   速度: 330.08KB/s | 数据量: 0.3KB | 总耗时: 0.40s
[2025-09-29 09:42:52] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/49/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.73s
[2025-09-29 09:42:52] ✅ 测速成功: http://111.202.12.159:8080/3zvkK28/1000/live.m3u8
   速度: 69.34KB/s | 数据量: 0.1KB | 总耗时: 0.40s
[2025-09-29 09:42:52] ✅ 测速成功: http://8.138.7.223/tv/hxws.m3u8
   速度: 211.91KB/s | 数据量: 0.2KB | 总耗时: 0.39s
[2025-09-29 09:42:52] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/38/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.80s
[2025-09-29 09:42:52] ✅ 测速成功: http://111.53.96.67:8081/live/1/index.m3u8
   速度: 208.98KB/s | 数据量: 0.2KB | 总耗时: 0.36s
[2025-09-29 09:42:52] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/22/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.75s
[2025-09-29 09:42:52] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/47/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.76s
[2025-09-29 09:42:52] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/36/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.76s
[2025-09-29 09:42:52] ✅ 测速成功: http://112.27.235.94:8000/hls/18/index.m3u8
   速度: 240.23KB/s | 数据量: 0.2KB | 总耗时: 1.31s
[2025-09-29 09:42:52] ✅ 测速成功: http://111.53.96.67:8081/live/1/index.m3u8?%E5%85%B3%E6%B3%A8%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7[%E6%99%B4%E5%9B%AD]
   速度: 208.98KB/s | 数据量: 0.2KB | 总耗时: 0.35s
[2025-09-29 09:42:52] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/46/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.80s
[2025-09-29 09:42:52] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/48/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.82s
[2025-09-29 09:42:54] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/34/live.m3u8
   速度: 0.16KB/s | 数据量: 0.2KB | 总耗时: 2.28s
[2025-09-29 09:42:55] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.241:8000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.241:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dc50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:55] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.159:8000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.159:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ce50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:55] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.158:8000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.158:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d250>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:55] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.242:8000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.242:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cb50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:55] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.116:8000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.116:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cc50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:55] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.117:8000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.117:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9da50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:55] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.115:8000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.115:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d550>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:55] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.189:8000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.189:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:56] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.243:8000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.243:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ca50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:57] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.235:8000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.235:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c350>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:58] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.129:8008
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.129:8008 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cf50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:58] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.60:8084
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.60:8084 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9df50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:58] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.172:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.172:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e350>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:58] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.105:8092
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.105:8092 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e650>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:58] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.173:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.173:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ea50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:58] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.130:8004
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.130:8004 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ee50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:58] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.174:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.174:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f250>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:58] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.61:8104
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.61:8104 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f650>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:42:59] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.175:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.175:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fa50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:00] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.62:8112
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.62:8112 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fe50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:01] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.63:8116
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.63:8116 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4250>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:01] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.152:8120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.152:8120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4550>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:01] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.64:8124
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.64:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:01] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.124:8128
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.124:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4b50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:01] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.65:8132
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.65:8132 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e650>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:01] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.153:8136
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.153:8136 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cf50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:01] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.184:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.184:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fb50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:01] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.151:8144
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.151:8144 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f750>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:02] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.132:8012
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.132:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f350>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:03] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.136:8032
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.136:8032 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ef50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:04] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.137:8036
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.137:8036 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9eb50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:04] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.135:8028
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.135:8028 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e750>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:04] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.134:8020
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.134:8020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e450>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:04] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.142:8048
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.142:8048 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e050>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:04] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.211:8064
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.211:8064 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:04] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.141:1234
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.141:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9db50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:04] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.122:8160
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.122:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4750>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:04] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.209:8052
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.209:8052 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4350>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:05] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.148:8072
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.148:8072 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4e50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:06] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.210:8056
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.210:8056 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5150>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:07] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.138:8044
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.138:8044 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ef50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:07] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.240:8172
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.240:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fb50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:07] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.149:8076
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.149:8076 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dc50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:07] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.156:8148
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.156:8148 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ce50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:07] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.123:8164
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.123:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c950>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:07] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.45:8304
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.45:8304 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cc50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:08] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.133:8016
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.133:8016 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fe50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:08] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.26:8108
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.26:8108 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fa50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:08] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.29:8288
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.29:8288 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f650>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:09] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.46:8124
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.46:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f250>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:10] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.42:8172
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.42:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9df50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:10] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.39:8300
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.39:8300 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4f50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:10] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.48:8160
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.48:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4450>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:10] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.27:8128
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.27:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4a50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:10] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.49:8188
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.49:8188 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:11] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.47:8164
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.47:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5450>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:11] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.44:8184
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.44:8184 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ce50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:11] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.41:8140
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.41:8140 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cc50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:11] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.43:8176
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.43:8176 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e350>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:12] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.155:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.155:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fc50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:13] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.143:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.143:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:13] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.144:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.144:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f050>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:13] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.236:2000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.236:2000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9db50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:13] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.249:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.249:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:13] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.250:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.250:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e050>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:14] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.95:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.95:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e450>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:14] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.100:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.100:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e750>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:14] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.238:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.238:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4250>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:14] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.102:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.102:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4950>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:15] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.213:4220
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.213:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4050>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:16] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.214:4220
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.214:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4e50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:16] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.215:4220
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.215:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5750>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:16] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.216:4220
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.216:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f050>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:16] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.217:4220
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.217:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e350>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:16] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.218:4220
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.218:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f750>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:17] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.219:4220
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.219:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dd50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:17] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.220:4220
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.220:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e150>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:17] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.57:8152
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.57:8152 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:17] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.54:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.54:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d550>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:18] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.56:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.56:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:19] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.188:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.188:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ee50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:20] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.163:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.163:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fb50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:20] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.221:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.221:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c350>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:20] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.96:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.96:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4750>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:20] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.154:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.154:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5050>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:20] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.187:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.187:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4b50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:20] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.58:8156
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.58:8156 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:20] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.165:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.165:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4f50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:20] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.164:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.164:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:21] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.94:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.94:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f750>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:23] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.92:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.92:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f050>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:23] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.91:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.91:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f650>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:23] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.93:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.93:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ca50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:23] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.74:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.74:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9da50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:23] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.195:9024
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.195:9024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d250>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:23] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.194:9020
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.194:9020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e650>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:23] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.68:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.68:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ce50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:23] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.67:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.67:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cc50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:23] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.90:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.90:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:24] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.196:9012
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.196:9012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4a50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:26] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.69:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.69:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4650>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:26] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.199:9000
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.199:9000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4350>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:26] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.80:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.80:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4e50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:26] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.51:9252
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.51:9252 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4250>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:26] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.147:9268
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.147:9268 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9da50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:26] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.71:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.71:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f050>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:26] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.75:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.75:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fc50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:26] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.76:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.76:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e050>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:26] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.85:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.85:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c650>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:28] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.77:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.77:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ec50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:29] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.83:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.83:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c350>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:29] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.81:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.81:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fb50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:29] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.52:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.52:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ee50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:29] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.78:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.78:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:29] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.193:8012
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.193:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac6050>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:29] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.79:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.79:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5750>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:29] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.86:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.86:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5d50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:29] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.87:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.87:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4150>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:29] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.73:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.73:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4b50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:31] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.72:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.72:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac6150>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:32] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.89:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.89:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ec50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:32] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.82:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.82:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fc50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:32] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.70:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.70:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e150>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:32] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.84:4120
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.84:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c950>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:32] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.125:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.125:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ef50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:32] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.126:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.126:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f450>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:32] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.127:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.127:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d850>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:32] ❌ 测速失败: http://114.241.210.205:4022/rtp/239.3.1.128:8001
   错误: HTTPConnectionPool(host='114.241.210.205', port=4022): Max retries exceeded with url: /rtp/239.3.1.128:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cc50>, 'Connection to 114.241.210.205 timed out. (connect timeout=3.05)')) | 域名: 114.241.210.205
[2025-09-29 09:43:32] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.138:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.138:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ce50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:34] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.107:8000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.107:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e650>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:35] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.108:8000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.108:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5450>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:35] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.117:8000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.117:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5050>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:35] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.118:8000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.118:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4450>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:35] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.119:8000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.119:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5a50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:35] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.120:8000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.120:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4250>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:35] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.122:8000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.122:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4650>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:35] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.23:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.23:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f450>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:35] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.29:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.29:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e150>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:35] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.129:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.129:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ca50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:37] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.130:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.130:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e850>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:38] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.3:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.3:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cf50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:38] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.131:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.131:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cb50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:38] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.5:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.5:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dc50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:38] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.18:9610
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.18:9610 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e350>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:38] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.6:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.6:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9da50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:38] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.254:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.254:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e050>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:38] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.8:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.8:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d250>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:38] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.53:9814
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.53:9814 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fe50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:38] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.134:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.134:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac6650>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:40] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.11:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.11:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4950>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:41] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.135:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.135:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4550>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:41] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.13:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.13:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4750>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:41] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.136:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.136:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dc50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:41] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.15:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.15:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e850>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:41] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.132:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.132:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9eb50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:41] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.139:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.139:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d550>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:41] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.140:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.140:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c650>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:41] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.141:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.141:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ee50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:41] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.142:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.142:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fa50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:43] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.143:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.143:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e750>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:44] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.145:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.145:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c850>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:44] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.146:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.146:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f650>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:44] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.147:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.147:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fc50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:44] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.148:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.148:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ef50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:44] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.188:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.188:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4850>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:44] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.204:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.204:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4050>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:44] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.185:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.185:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4650>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:44] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.149:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.149:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4450>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:44] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.144:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.144:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fa50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:46] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.49:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.49:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d550>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:47] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.53:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.53:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c950>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:47] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.35:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.35:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ec50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:47] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.40:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.40:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e650>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:47] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.41:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.41:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9df50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:47] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.43:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.43:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dd50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:47] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.44:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.44:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fb50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:47] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.45:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.45:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f450>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:47] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.51:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.51:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e150>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:47] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.52:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.52:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ca50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:49] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.1.235:6000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.1.235:6000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cb50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:50] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.0.25:8192
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.0.25:8192 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5a50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:50] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.0.183:9434
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.0.183:9434 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4e50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:50] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.0.26:8200
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.0.26:8200 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac6450>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:50] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.0.9:8064
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.0.9:8064 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4550>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:50] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.19:9614
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.19:9614 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dd50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:50] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.50:9802
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.50:9802 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ec50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:50] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.54:9818
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.54:9818 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cf50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:50] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.55:9822
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.55:9822 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ea50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:50] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.56:9826
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.56:9826 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e050>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:52] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.52:9810
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.52:9810 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f050>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:53] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.16:9602
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.16:9602 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f250>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:53] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.12:9418
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.12:9418 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f350>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:53] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.20:9618
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.20:9618 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ce50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:53] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.11:9414
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.11:9414 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cc50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:53] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.17:9606
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.17:9606 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9eb50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:53] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.13:9422
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.13:9422 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ee50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:53] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.7:9306
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.7:9306 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4950>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:53] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.15:9430
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.15:9430 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4f50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:54] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.57:9830
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.57:9830 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4250>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:55] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.48:8000
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.48:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4450>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:56] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.14:9426
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.14:9426 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4850>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:56] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.8:9632
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.8:9632 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f250>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:56] ❌ 测速失败: http://49.77.104.96:8554/rtp/239.49.8.35:8620
   错误: HTTPConnectionPool(host='49.77.104.96', port=8554): Max retries exceeded with url: /rtp/239.49.8.35:8620 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ea50>, 'Connection to 49.77.104.96 timed out. (connect timeout=3.05)')) | 域名: 49.77.104.96
[2025-09-29 09:43:59] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.236:5140
   速度: 553.18KB/s | 数据量: 3072.0KB | 总耗时: 5.93s
[2025-09-29 09:43:59] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.209:5140
   速度: 518.46KB/s | 数据量: 3072.0KB | 总耗时: 6.30s
[2025-09-29 09:44:00] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.146:5140
   速度: 502.11KB/s | 数据量: 3072.0KB | 总耗时: 6.48s
[2025-09-29 09:44:00] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.136:5140
   速度: 501.80KB/s | 数据量: 3072.0KB | 总耗时: 6.49s
[2025-09-29 09:44:01] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.237:5140
   速度: 414.64KB/s | 数据量: 3072.0KB | 总耗时: 7.78s
[2025-09-29 09:44:06] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.132:5140
   速度: 307.79KB/s | 数据量: 2048.0KB | 总耗时: 7.03s
[2025-09-29 09:44:07] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.131:5140
   速度: 547.03KB/s | 数据量: 4096.0KB | 总耗时: 7.87s
[2025-09-29 09:44:08] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.196:5140
   速度: 142.92KB/s | 数据量: 2048.0KB | 总耗时: 14.71s
[2025-09-29 09:44:09] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.210:5140
   速度: 388.74KB/s | 数据量: 3072.0KB | 总耗时: 8.29s
[2025-09-29 09:44:09] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.134:5140
   速度: 74.07KB/s | 数据量: 1024.0KB | 总耗时: 14.48s
[2025-09-29 09:44:10] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.13:5140
   速度: 312.26KB/s | 数据量: 3072.0KB | 总耗时: 10.22s
[2025-09-29 09:44:11] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.17:5140
   速度: 189.43KB/s | 数据量: 2048.0KB | 总耗时: 11.19s
[2025-09-29 09:44:13] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.211:5140
   速度: 353.82KB/s | 数据量: 2048.0KB | 总耗时: 6.15s
[2025-09-29 09:44:13] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.135:5140
   速度: 766.57KB/s | 数据量: 4096.0KB | 总耗时: 5.72s
[2025-09-29 09:44:13] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.46:5140
   速度: 62.71KB/s | 数据量: 1024.0KB | 总耗时: 17.09s
[2025-09-29 09:44:14] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.9:5140
   速度: 60.94KB/s | 数据量: 1024.0KB | 总耗时: 17.55s
[2025-09-29 09:44:15] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.55:5140
   速度: 55.67KB/s | 数据量: 1024.0KB | 总耗时: 19.15s
[2025-09-29 09:44:18] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.69:5140
   速度: 315.24KB/s | 数据量: 2048.0KB | 总耗时: 6.89s
[2025-09-29 09:44:18] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.208:5140
   速度: 245.47KB/s | 数据量: 2048.0KB | 总耗时: 8.72s
[2025-09-29 09:44:18] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.145:5140
   速度: 422.76KB/s | 数据量: 4096.0KB | 总耗时: 10.08s
[2025-09-29 09:44:19] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.70:5140
   速度: 166.71KB/s | 数据量: 1024.0KB | 总耗时: 6.51s
[2025-09-29 09:44:20] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.4:5140
   速度: 166.22KB/s | 数据量: 1024.0KB | 总耗时: 6.55s
[2025-09-29 09:44:20] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.56:5140
   速度: 143.37KB/s | 数据量: 1024.0KB | 总耗时: 7.53s
[2025-09-29 09:44:23] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.8:5140
   速度: 588.56KB/s | 数据量: 4096.0KB | 总耗时: 7.35s
[2025-09-29 09:44:24] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.2:5140
   速度: 72.45KB/s | 数据量: 1024.0KB | 总耗时: 14.52s
[2025-09-29 09:44:25] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.196:5140
   速度: 316.26KB/s | 数据量: 2048.0KB | 总耗时: 6.85s
[2025-09-29 09:44:26] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.10:5140
   速度: 424.72KB/s | 数据量: 3072.0KB | 总耗时: 7.61s
[2025-09-29 09:44:26] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.198:5140
   速度: 288.31KB/s | 数据量: 2048.0KB | 总耗时: 7.47s
[2025-09-29 09:44:29] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.200:5140
   速度: 125.92KB/s | 数据量: 1024.0KB | 总耗时: 8.51s
[2025-09-29 09:44:29] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.68:5140
   速度: 105.41KB/s | 数据量: 2048.0KB | 总耗时: 19.81s
[2025-09-29 09:44:31] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.71:5140
   速度: 124.57KB/s | 数据量: 2048.0KB | 总耗时: 17.81s
[2025-09-29 09:44:31] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.4:5140
   速度: 250.59KB/s | 数据量: 2048.0KB | 总耗时: 8.55s
[2025-09-29 09:44:31] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.52:5140
   速度: 97.43KB/s | 数据量: 1024.0KB | 总耗时: 10.88s
[2025-09-29 09:44:31] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.42:5140
   速度: 622.26KB/s | 数据量: 4096.0KB | 总耗时: 6.96s
[2025-09-29 09:44:33] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.107:5140
   速度: 297.63KB/s | 数据量: 2048.0KB | 总耗时: 7.27s
[2025-09-29 09:44:35] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.29:5140
   速度: 408.22KB/s | 数据量: 2048.0KB | 总耗时: 5.40s
[2025-09-29 09:44:37] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.139:5140
   速度: 276.30KB/s | 数据量: 2048.0KB | 总耗时: 7.79s
[2025-09-29 09:44:38] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.10:5140
   速度: 268.19KB/s | 数据量: 3072.0KB | 总耗时: 11.83s
[2025-09-29 09:44:38] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.229:5140
   速度: 659.81KB/s | 数据量: 4096.0KB | 总耗时: 6.59s
[2025-09-29 09:44:38] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.23:5140
   速度: 56.25KB/s | 数据量: 1024.0KB | 总耗时: 18.91s
[2025-09-29 09:44:39] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.239:5140
   速度: 140.56KB/s | 数据量: 1024.0KB | 总耗时: 7.67s
[2025-09-29 09:44:40] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.1:5140
   速度: 67.97KB/s | 数据量: 1024.0KB | 总耗时: 15.45s
[2025-09-29 09:44:41] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.228:5140
   速度: 143.33KB/s | 数据量: 1024.0KB | 总耗时: 7.51s
[2025-09-29 09:44:42] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.124:5140
   速度: 460.61KB/s | 数据量: 3072.0KB | 总耗时: 7.05s
[2025-09-29 09:44:42] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.120:5140
   速度: 576.69KB/s | 数据量: 3072.0KB | 总耗时: 5.70s
[2025-09-29 09:44:44] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.178:5140
   速度: 160.51KB/s | 数据量: 2048.0KB | 总耗时: 13.14s
[2025-09-29 09:44:44] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.177:5140
   速度: 158.69KB/s | 数据量: 2048.0KB | 总耗时: 13.29s
[2025-09-29 09:44:44] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.121:5140
   速度: 677.07KB/s | 数据量: 4096.0KB | 总耗时: 6.42s
[2025-09-29 09:44:50] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.122:5140
   速度: 220.47KB/s | 数据量: 2048.0KB | 总耗时: 9.67s
[2025-09-29 09:44:50] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.44:5140
   速度: 219.45KB/s | 数据量: 2048.0KB | 总耗时: 9.72s
[2025-09-29 09:44:50] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.83:5140
   速度: 557.63KB/s | 数据量: 3072.0KB | 总耗时: 5.89s
[2025-09-29 09:44:51] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.231:5140
   速度: 479.02KB/s | 数据量: 3072.0KB | 总耗时: 6.79s
[2025-09-29 09:44:51] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.84:5140
   速度: 319.84KB/s | 数据量: 2048.0KB | 总耗时: 6.78s
[2025-09-29 09:44:53] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.238:5140
   速度: 75.38KB/s | 数据量: 1024.0KB | 总耗时: 14.97s
[2025-09-29 09:44:54] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.3:5140
   速度: 254.43KB/s | 数据量: 3072.0KB | 总耗时: 12.45s
[2025-09-29 09:44:55] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.5:5140
   速度: 66.24KB/s | 数据量: 1024.0KB | 总耗时: 16.05s
[2025-09-29 09:44:56] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.81:5140
   速度: 153.18KB/s | 数据量: 2048.0KB | 总耗时: 13.75s
[2025-09-29 09:44:56] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.4:5140
   速度: 821.89KB/s | 数据量: 5120.0KB | 总耗时: 6.59s
[2025-09-29 09:44:57] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.6:5140
   速度: 661.66KB/s | 数据量: 4096.0KB | 总耗时: 6.56s
[2025-09-29 09:44:58] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.80:5140
   速度: 576.49KB/s | 数据量: 4096.0KB | 总耗时: 7.48s
[2025-09-29 09:44:59] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.123:5140
   速度: 128.32KB/s | 数据量: 1024.0KB | 总耗时: 8.37s
[2025-09-29 09:45:01] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.230:5140
   速度: 46.74KB/s | 数据量: 1024.0KB | 总耗时: 23.29s
[2025-09-29 09:45:01] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.230:5140
   速度: 306.11KB/s | 数据量: 2048.0KB | 总耗时: 7.07s
[2025-09-29 09:45:02] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.232:5140
   速度: 96.95KB/s | 数据量: 1024.0KB | 总耗时: 10.95s
[2025-09-29 09:45:02] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.213:5140
   速度: 340.82KB/s | 数据量: 2048.0KB | 总耗时: 6.39s
[2025-09-29 09:45:03] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.4:5140
   速度: 765.99KB/s | 数据量: 4096.0KB | 总耗时: 5.72s
[2025-09-29 09:45:03] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.232:5140
   速度: 337.35KB/s | 数据量: 2048.0KB | 总耗时: 6.45s
[2025-09-29 09:45:06] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.234:5140
   速度: 128.78KB/s | 数据量: 1024.0KB | 总耗时: 8.34s
[2025-09-29 09:45:08] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.231:5140
   速度: 78.55KB/s | 数据量: 1024.0KB | 总耗时: 13.42s
[2025-09-29 09:45:08] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.38:5140
   速度: 197.57KB/s | 数据量: 1024.0KB | 总耗时: 5.56s
[2025-09-29 09:45:09] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.3:5140
   速度: 141.36KB/s | 数据量: 1024.0KB | 总耗时: 7.61s
[2025-09-29 09:45:09] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.117:5140
   速度: 336.85KB/s | 数据量: 2048.0KB | 总耗时: 6.44s
[2025-09-29 09:45:09] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.82:5140
   速度: 328.26KB/s | 数据量: 2048.0KB | 总耗时: 6.63s
[2025-09-29 09:45:09] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.251:5140
   速度: 316.98KB/s | 数据量: 2048.0KB | 总耗时: 6.84s
[2025-09-29 09:45:11] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.238:5140
   速度: 178.82KB/s | 数据量: 2048.0KB | 总耗时: 11.83s
[2025-09-29 09:45:13] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.229:5140
   速度: 55.46KB/s | 数据量: 1024.0KB | 总耗时: 20.87s
[2025-09-29 09:45:14] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.0.8:5140
   速度: 402.38KB/s | 数据量: 2048.0KB | 总耗时: 5.47s
[2025-09-29 09:45:15] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.125:5140
   速度: 355.22KB/s | 数据量: 2048.0KB | 总耗时: 6.14s
[2025-09-29 09:45:15] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.45:5140
   速度: 243.09KB/s | 数据量: 2048.0KB | 总耗时: 8.80s
[2025-09-29 09:45:15] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.14:5140
   速度: 503.26KB/s | 数据量: 3072.0KB | 总耗时: 6.48s
[2025-09-29 09:45:15] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.116:5140
   速度: 76.45KB/s | 数据量: 1024.0KB | 总耗时: 13.78s
[2025-09-29 09:45:16] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.194:5140
   速度: 345.08KB/s | 数据量: 2048.0KB | 总耗时: 6.32s
[2025-09-29 09:45:17] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.52:5140
   速度: 268.89KB/s | 数据量: 2048.0KB | 总耗时: 7.99s
[2025-09-29 09:45:19] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.185:5140
   速度: 142.64KB/s | 数据量: 1024.0KB | 总耗时: 7.56s
[2025-09-29 09:45:19] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.74:5140
   速度: 811.81KB/s | 数据量: 4096.0KB | 总耗时: 5.43s
[2025-09-29 09:45:20] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.48:5140
   速度: 343.24KB/s | 数据量: 2048.0KB | 总耗时: 6.35s
[2025-09-29 09:45:20] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.111:5002
   速度: 1223.43KB/s | 数据量: 6144.0KB | 总耗时: 5.50s
[2025-09-29 09:45:21] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.130:5002
   速度: 1227.93KB/s | 数据量: 6144.0KB | 总耗时: 5.48s
[2025-09-29 09:45:21] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.1.50:5140
   速度: 91.16KB/s | 数据量: 1024.0KB | 总耗时: 11.61s
[2025-09-29 09:45:21] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.207:5140
   速度: 548.33KB/s | 数据量: 3072.0KB | 总耗时: 5.98s
[2025-09-29 09:45:21] ✅ 测速成功: http://223.167.245.215:8001/rtp/239.45.3.75:5140
   速度: 882.46KB/s | 数据量: 5120.0KB | 总耗时: 6.16s
[2025-09-29 09:45:22] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.149:5002
   速度: 1226.10KB/s | 数据量: 6144.0KB | 总耗时: 5.52s
[2025-09-29 09:45:22] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.131:5002
   速度: 1225.96KB/s | 数据量: 7168.0KB | 总耗时: 6.37s
[2025-09-29 09:45:23] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.158:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.58s
[2025-09-29 09:45:23] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.151:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.98s
[2025-09-29 09:45:23] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.133:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.60s
[2025-09-29 09:45:23] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.120:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.79s
[2025-09-29 09:45:23] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.123:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.93s
[2025-09-29 09:45:24] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.128:5002
   速度: 1227.46KB/s | 数据量: 6144.0KB | 总耗时: 5.54s
[2025-09-29 09:45:25] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.122:5002
   速度: 1226.46KB/s | 数据量: 6144.0KB | 总耗时: 5.50s
[2025-09-29 09:45:25] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.129:5002
   速度: 1224.97KB/s | 数据量: 6144.0KB | 总耗时: 5.52s
[2025-09-29 09:45:26] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.196:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-29 09:45:26] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.138:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:26] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.119:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:26] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.121:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:27] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.192:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.60s
[2025-09-29 09:45:27] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.140:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.02s
[2025-09-29 09:45:28] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.160:5002
   速度: 1125.96KB/s | 数据量: 6144.0KB | 总耗时: 5.98s
[2025-09-29 09:45:28] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.150:5002
   速度: 1117.02KB/s | 数据量: 6144.0KB | 总耗时: 5.99s
[2025-09-29 09:45:29] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.195:5002
   速度: 1129.20KB/s | 数据量: 6144.0KB | 总耗时: 5.94s
[2025-09-29 09:45:29] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.144:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:29] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.194:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-29 09:45:30] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.52:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:30] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.215:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:31] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.142:5002
   速度: 1120.44KB/s | 数据量: 6144.0KB | 总耗时: 5.98s
[2025-09-29 09:45:32] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.237:5002
   速度: 943.51KB/s | 数据量: 5120.0KB | 总耗时: 5.93s
[2025-09-29 09:45:32] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.173:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:32] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.175:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.07s
[2025-09-29 09:45:32] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.174:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:33] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.193:5002
   速度: 1081.60KB/s | 数据量: 6144.0KB | 总耗时: 6.16s
[2025-09-29 09:45:33] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.176:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:34] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.213:5002
   速度: 1126.47KB/s | 数据量: 6144.0KB | 总耗时: 5.99s
[2025-09-29 09:45:34] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.169:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.12s
[2025-09-29 09:45:35] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.214:5002
   速度: 1041.54KB/s | 数据量: 6144.0KB | 总耗时: 6.44s
[2025-09-29 09:45:35] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.177:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:35] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.171:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:35] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.166:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:35] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.170:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.85s
[2025-09-29 09:45:36] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.168:5002
   速度: 1127.50KB/s | 数据量: 6144.0KB | 总耗时: 5.97s
[2025-09-29 09:45:37] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.112:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.88s
[2025-09-29 09:45:38] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.116:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-29 09:45:38] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.147:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:39] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.167:5002
   速度: 933.24KB/s | 数据量: 5120.0KB | 总耗时: 6.00s
[2025-09-29 09:45:39] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.114:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.03s
[2025-09-29 09:45:40] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.172:5002
   速度: 923.94KB/s | 数据量: 6144.0KB | 总耗时: 7.23s
[2025-09-29 09:45:40] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.127:5002
   速度: 971.05KB/s | 数据量: 5120.0KB | 总耗时: 5.84s
[2025-09-29 09:45:41] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.113:5002
   速度: 1130.08KB/s | 数据量: 6144.0KB | 总耗时: 6.10s
[2025-09-29 09:45:41] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.31:5002
   速度: 1132.65KB/s | 数据量: 6144.0KB | 总耗时: 5.96s
[2025-09-29 09:45:41] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.81:5002
   速度: 1127.96KB/s | 数据量: 6144.0KB | 总耗时: 5.98s
[2025-09-29 09:45:41] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.126:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-29 09:45:42] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.123:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 4.00s
[2025-09-29 09:45:42] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.155:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:42] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.29:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:42] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.154:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.84s
[2025-09-29 09:45:42] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.117:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.47s
[2025-09-29 09:45:43] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.26:5002
   速度: 408.62KB/s | 数据量: 2048.0KB | 总耗时: 5.55s
[2025-09-29 09:45:45] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.32:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:45] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.115:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:45] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.56:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:45] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.41:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.44s
[2025-09-29 09:45:47] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.28:5002
   速度: 1127.13KB/s | 数据量: 6144.0KB | 总耗时: 6.00s
[2025-09-29 09:45:47] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.82:5002
   速度: 1130.14KB/s | 数据量: 6144.0KB | 总耗时: 5.98s
[2025-09-29 09:45:47] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.27:5002
   速度: 1125.90KB/s | 数据量: 6144.0KB | 总耗时: 5.98s
[2025-09-29 09:45:47] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.61:5002
   速度: 1124.79KB/s | 数据量: 6144.0KB | 总耗时: 5.97s
[2025-09-29 09:45:48] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.51:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-29 09:45:48] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.61:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:48] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.35:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:48] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.30:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:49] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.54:5002
   速度: 330.07KB/s | 数据量: 2048.0KB | 总耗时: 6.82s
[2025-09-29 09:45:49] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.50:5002
   速度: 329.37KB/s | 数据量: 2048.0KB | 总耗时: 6.89s
[2025-09-29 09:45:49] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.181:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.90s
[2025-09-29 09:45:50] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.124:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.03s
[2025-09-29 09:45:50] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.118:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.04s
[2025-09-29 09:45:50] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.57:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.07s
[2025-09-29 09:45:51] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.134:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:52] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.139:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.14s
[2025-09-29 09:45:52] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.237:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.03s
[2025-09-29 09:45:52] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.146:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.21s
[2025-09-29 09:45:54] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.236:5002
   速度: 1131.09KB/s | 数据量: 6144.0KB | 总耗时: 5.93s
[2025-09-29 09:45:54] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.141:5002
   速度: 1128.69KB/s | 数据量: 6144.0KB | 总耗时: 5.98s
[2025-09-29 09:45:54] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.247:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-29 09:45:54] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.19:5002
   速度: 1122.22KB/s | 数据量: 6144.0KB | 总耗时: 6.02s
[2025-09-29 09:45:55] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.236:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.97s
[2025-09-29 09:45:55] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.105:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.97s
[2025-09-29 09:45:55] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.104:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.97s
[2025-09-29 09:45:56] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.135:5002
   速度: 1133.70KB/s | 数据量: 6144.0KB | 总耗时: 5.96s
[2025-09-29 09:45:56] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.145:5002
   速度: 1125.89KB/s | 数据量: 6144.0KB | 总耗时: 5.99s
[2025-09-29 09:45:56] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.143:5002
   速度: 1121.64KB/s | 数据量: 6144.0KB | 总耗时: 6.00s
[2025-09-29 09:45:57] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.129:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.08s
[2025-09-29 09:45:57] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.57:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.02s
[2025-09-29 09:45:57] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.207:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.98s
[2025-09-29 09:45:57] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.137:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-29 09:45:59] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.4:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:59] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.2:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:45:59] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.110:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.04s
[2025-09-29 09:46:00] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.8:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:46:01] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.82:5002
   速度: 1110.56KB/s | 数据量: 6144.0KB | 总耗时: 6.04s
[2025-09-29 09:46:02] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.27:5002
   速度: 329.85KB/s | 数据量: 2048.0KB | 总耗时: 6.80s
[2025-09-29 09:46:02] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.55:5002
   速度: 330.09KB/s | 数据量: 2048.0KB | 总耗时: 6.82s
[2025-09-29 09:46:02] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.62:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:46:02] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.58:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:46:02] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.216:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:46:03] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.205:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-29 09:46:04] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.14:5002
   速度: 1105.43KB/s | 数据量: 6144.0KB | 总耗时: 6.07s
[2025-09-29 09:46:04] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.171:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.95s
[2025-09-29 09:46:05] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.83:5002
   速度: 311.17KB/s | 数据量: 2048.0KB | 总耗时: 7.21s
[2025-09-29 09:46:05] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.2.7:5002
   速度: 305.16KB/s | 数据量: 2048.0KB | 总耗时: 7.36s
[2025-09-29 09:46:05] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.176:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:46:05] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.175:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:46:05] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.174:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-29 09:46:05] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.173:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.18s
[2025-09-29 09:46:08] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.126:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.126:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:09] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.154:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.154:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e450>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:09] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.25:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.25:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fe50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:09] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.164:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.164:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9da50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:09] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.150:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.150:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c950>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:09] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.172:5002
   速度: 329.64KB/s | 数据量: 2048.0KB | 总耗时: 6.86s
[2025-09-29 09:46:10] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.177:5002
   速度: 326.34KB/s | 数据量: 2048.0KB | 总耗时: 6.88s
[2025-09-29 09:46:10] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.178:5002
   速度: 330.17KB/s | 数据量: 2048.0KB | 总耗时: 6.80s
[2025-09-29 09:46:11] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.241:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.241:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:11] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.179:5002
   速度: 330.21KB/s | 数据量: 2048.0KB | 总耗时: 6.80s
[2025-09-29 09:46:12] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.151:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.151:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5150>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:12] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.156:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.156:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac6450>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:12] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.165:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.165:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5750>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:12] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.168:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.168:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4b50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:12] ✅ 测速成功: http://111.162.205.166:8686/rtp/225.1.1.180:5002
   速度: 301.78KB/s | 数据量: 2048.0KB | 总耗时: 7.40s
[2025-09-29 09:46:12] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.27:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.27:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e850>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:13] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.135:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.135:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e350>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:13] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.170:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.170:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:14] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.201:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.201:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c950>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:14] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.171:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.171:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c350>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:15] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.93:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.93:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e450>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:15] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.172:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.172:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:15] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.173:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.173:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d550>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:15] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.136:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.136:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e150>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:15] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.137:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.137:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9df50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:15] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.138:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.138:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d250>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:16] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.178:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.178:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ef50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:16] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.139:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.139:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ee50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:17] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.15:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.15:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9eb50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:17] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.140:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.140:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cc50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:18] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.179:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.179:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ce50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:18] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.182:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.182:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:18] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.230:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.230:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5a50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:18] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.29:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.29:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac6650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:18] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.38:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.38:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4350>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:18] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.45:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.45:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5050>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:19] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.52:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.52:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ef50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:19] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.47:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.47:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e150>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:20] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.60:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.60:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f050>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:20] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.56:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.56:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cf50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:21] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.63:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.63:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e750>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:21] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.58:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.58:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c850>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:21] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.51:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.51:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f750>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:21] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.206:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.206:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f850>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:21] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.117:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.117:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ca50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:21] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.125:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.125:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f450>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:23] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.122:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.122:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ea50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:23] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.123:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.123:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4450>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:23] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.116:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.116:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4050>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:23] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.141:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.141:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4550>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:24] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.115:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.115:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac6250>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:24] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.181:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.181:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4b50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:24] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.131:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.131:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f750>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:24] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.130:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.130:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e750>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:24] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.124:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.124:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e150>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:24] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.185:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.185:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ef50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:26] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.186:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.186:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fa50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:26] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.74:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.74:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cb50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:26] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.110:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.110:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:27] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.26:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.26:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dd50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:27] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.95:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.95:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ec50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:27] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.82:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.82:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e050>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:27] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.49:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.49:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d550>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:27] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.80:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.80:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9d250>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:27] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.101:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.101:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5750>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:27] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.40:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.40:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4750>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:29] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.35:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.35:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4850>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:29] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.111:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.111:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac6650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:29] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.34:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.34:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:30] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.180:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.180:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ef50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:30] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.76:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.76:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9df50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:30] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.50:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.50:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c950>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:30] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.86:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.86:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:30] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.18:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.18:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cc50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:30] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.114:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.114:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e350>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:30] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.160:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.160:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ea50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:32] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.212:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.212:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f450>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:32] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.238:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.238:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ca50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:32] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.239:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.239:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f850>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:33] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.169:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.169:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:33] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.67:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.67:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5050>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:33] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.161:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.161:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4e50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:33] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.163:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.163:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5150>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:33] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.90:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.90:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4550>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:33] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.162:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.162:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4250>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:34] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.98:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.98:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e350>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:35] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.108:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.108:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c850>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:35] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.107:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.107:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c950>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:35] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.127:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.127:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cf50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:36] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.128:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.128:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:36] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.133:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.133:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9db50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:36] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.134:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.134:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dc50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:36] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.53:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.53:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9eb50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:36] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.149:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.149:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c350>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:37] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.59:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.59:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ee50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:37] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.188:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.188:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e150>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:38] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.198:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.198:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cb50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:38] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.28:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.28:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac6250>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:38] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.6:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.6:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac6050>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:39] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.43:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.43:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4350>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:39] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.8:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.8:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4850>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:39] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.103:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.103:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dc50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:39] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.159:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.159:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cf50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:39] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.157:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.157:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fa50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:40] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.57:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.57:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e750>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:40] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.104:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.104:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e050>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:41] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.105:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.105:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ce50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:41] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.109:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.109:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e850>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:41] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.102:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.102:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9da50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:42] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.213:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.213:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:42] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.148:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.148:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ef50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:42] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.118:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.118:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e650>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:42] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.119:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.119:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4750>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:42] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.187:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.187:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5450>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:42] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-29 09:46:43] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:43] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.203:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.203:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4b50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:43] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.197:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.197:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4550>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:43] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0004_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:43] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0004_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:43] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.42s
[2025-09-29 09:46:44] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1020_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.42s
[2025-09-29 09:46:44] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.155:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.155:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e850>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:44] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.48:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.48:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5050>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:44] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/faacts/0006_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 290.04KB/s | 数据量: 0.3KB | 总耗时: 0.40s
[2025-09-29 09:46:44] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0006_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:45] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.214:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.214:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e750>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:45] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:45] ❌ 测速失败: http://116.2.171.154:4010/rtp/232.0.0.215:1234
   错误: HTTPConnectionPool(host='116.2.171.154', port=4010): Max retries exceeded with url: /rtp/232.0.0.215:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cc50>, 'Connection to 116.2.171.154 timed out. (connect timeout=3.05)')) | 域名: 116.2.171.154
[2025-09-29 09:46:45] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0008_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:45] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9df50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:45] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cb50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:45] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:46] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0003_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0003_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f250>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:46] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0010_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:46] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0004_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0004_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e150>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:46] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0011_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:46] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0011_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:46] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0005_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0005_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ee50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:46] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0012_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:46] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0012_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 423.83KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:47] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0013_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-29 09:46:47] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1052_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-29 09:46:47] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0006_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0006_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f850>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:47] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1046_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:47] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0014_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:47] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0007_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0007_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9eb50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:48] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0008_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0008_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4450>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:48] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0107_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-29 09:46:48] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0115_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 407.23KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-29 09:46:48] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0109_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 407.23KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:48] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1022_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:48] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0009_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0009_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c350>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:48] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0116_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 407.23KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:48] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0010_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0010_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac5a50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:48] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0011_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0011_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4e50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:48] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0123_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 407.23KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:48] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1084_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:49] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1044_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:49] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0130_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:49] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0130_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 396.48KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:49] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0118_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 428.71KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:49] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0012_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0012_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e150>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:49] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1025_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:49] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1087_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:49] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0127_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:49] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0139_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:49] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0124_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-29 09:46:49] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1027_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:49] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/0128_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-29 09:46:49] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0013_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0013_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9e750>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:49] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0141_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 407.23KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:49] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1032_1.m3u8?key=txiptv&playlive=0&authid=0
   速度: 657.23KB/s | 数据量: 0.7KB | 总耗时: 0.40s
[2025-09-29 09:46:49] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/0142_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 407.23KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:50] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1040_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:50] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1014_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:50] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1012_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.42s
[2025-09-29 09:46:50] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1011_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:50] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1008_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:50] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1009_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:50] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0014_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0014_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9df50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:50] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1010_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:50] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:50] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1072_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:50] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1136_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:50] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1071_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-29 09:46:50] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0015_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0015_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9cb50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:50] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1138_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:50] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1135_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:50] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1017_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.42s
[2025-09-29 09:46:50] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1004_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.42s
[2025-09-29 09:46:50] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1048_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1000_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1028_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1061_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1062_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1001_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1076_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1015_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:51] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1013_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1080_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1085_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1063_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:51] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1064_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:52] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1031_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:52] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/0139_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/0139_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dd50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:52] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1002_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-29 09:46:52] ✅ 测速成功: http://221.13.235.126:9901/tsfile/live/1016_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:52] ✅ 测速成功: http://116.11.156.4:8811/tsfile/live/1034_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-29 09:46:52] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/1008_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/1008_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9fa50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:53] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/1010_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/1010_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ca50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:54] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/1007_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/1007_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4850>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:54] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/1009_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/1009_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9ce50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:54] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/1006_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/1006_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9dc50>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:54] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/1002_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/1002_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9c950>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:54] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/1005_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/1005_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860d9f750>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
[2025-09-29 09:46:55] ❌ 测速失败: http://221.13.235.171:9901/tsfile/live/1001_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='221.13.235.171', port=9901): Max retries exceeded with url: /tsfile/live/1001_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6860ac4350>, 'Connection to 221.13.235.171 timed out. (connect timeout=3.05)')) | 域名: 221.13.235.171
