测速日志 2025-09-18 09:27:55
[2025-09-18 09:27:58] ✅ 测速成功: http://61.221.215.25:8800/hls/43/index.m3u8
   速度: 236.33KB/s | 数据量: 0.2KB | 总耗时: 0.39s
[2025-09-18 09:27:58] ✅ 测速成功: http://8.138.7.223/【公众号：榴芒电视】/cctv7.m3u8
   速度: 209.96KB/s | 数据量: 0.2KB | 总耗时: 0.49s
[2025-09-18 09:27:58] ✅ 测速成功: http://8.138.7.223/tv/cctv7.m3u8
   速度: 132.81KB/s | 数据量: 0.1KB | 总耗时: 0.49s
[2025-09-18 09:27:58] ✅ 测速成功: http://61.162.52.6:8088/newlive/live/hls/60/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.51s
[2025-09-18 09:27:58] ✅ 测速成功: http://123.146.162.24:8013/tslslive/PU2vzMI/hls/live_sd.m3u8?zzhongqd
   速度: 545.90KB/s | 数据量: 0.5KB | 总耗时: 0.52s
[2025-09-18 09:27:58] ✅ 测速成功: http://123.146.162.24:8017/c2F0hmi/1000/live.m3u8
   速度: 438.48KB/s | 数据量: 0.4KB | 总耗时: 0.53s
[2025-09-18 09:27:58] ✅ 测速成功: http://120.198.95.220:9901/tsfile/live/1071_1.m3u8?key=txiptv
   速度: 658.20KB/s | 数据量: 0.7KB | 总耗时: 0.65s
[2025-09-18 09:27:58] ✅ 测速成功: http://120.198.95.220:9901/tsfile/live/1038_1.m3u8?key=txiptv
   速度: 658.20KB/s | 数据量: 0.7KB | 总耗时: 0.65s
[2025-09-18 09:27:58] ✅ 测速成功: http://60.222.246.220:19433/hls1.m3u8
   速度: 0.72KB/s | 数据量: 0.2KB | 总耗时: 0.82s
[2025-09-18 09:27:58] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/33/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.90s
[2025-09-18 09:27:58] ✅ 测速成功: http://112.27.235.94:8000/hls/18/index.m3u8
   速度: 240.23KB/s | 数据量: 0.2KB | 总耗时: 0.42s
[2025-09-18 09:27:58] ✅ 测速成功: http://8.138.7.223/【公众号：榴芒电视】/农林卫视.m3u8
   速度: 118.16KB/s | 数据量: 0.1KB | 总耗时: 0.50s
[2025-09-18 09:27:59] ✅ 测速成功: http://123.146.162.24:8013/tslslive/noEX9SG/hls/live_sd.m3u8?zzhongqd
   速度: 545.90KB/s | 数据量: 0.5KB | 总耗时: 0.52s
[2025-09-18 09:27:59] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/45/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.93s
[2025-09-18 09:27:59] ✅ 测速成功: http://112.27.235.94:8000/hls/25/index.m3u8
   速度: 240.23KB/s | 数据量: 0.2KB | 总耗时: 0.43s
[2025-09-18 09:27:59] ✅ 测速成功: http://124.88.144.73:1935/live/xwzh/playlist.m3u8?zxinjd
   速度: 0.49KB/s | 数据量: 0.1KB | 总耗时: 0.89s
[2025-09-18 09:27:59] ✅ 测速成功: http://124.88.144.73:1935/live/dywt/playlist.m3u8?zxinjd
   速度: 0.50KB/s | 数据量: 0.1KB | 总耗时: 0.87s
[2025-09-18 09:27:59] ✅ 测速成功: http://124.88.144.73:1935/live/jiaoyu/playlist.m3u8
   速度: 0.45KB/s | 数据量: 0.1KB | 总耗时: 0.90s
[2025-09-18 09:27:59] ✅ 测速成功: http://222.128.55.152:9080/live/dwq.m3u8
   速度: 0.34KB/s | 数据量: 0.1KB | 总耗时: 0.77s
[2025-09-18 09:27:59] ✅ 测速成功: http://8.138.7.223/tv/gzjs.m3u8
   速度: 133.79KB/s | 数据量: 0.1KB | 总耗时: 0.49s
[2025-09-18 09:27:59] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/49/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.91s
[2025-09-18 09:27:59] ✅ 测速成功: http://111.202.12.159:8080/kYGHWzA/1000/live.m3u8
   速度: 330.08KB/s | 数据量: 0.3KB | 总耗时: 0.51s
[2025-09-18 09:27:59] ✅ 测速成功: http://124.88.144.73:1935/live/dywt/playlist.m3u8
   速度: 0.46KB/s | 数据量: 0.1KB | 总耗时: 0.88s
[2025-09-18 09:27:59] ✅ 测速成功: http://111.202.12.159:8080/3zvkK28/1000/live.m3u8
   速度: 69.34KB/s | 数据量: 0.1KB | 总耗时: 0.51s
[2025-09-18 09:27:59] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/38/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.90s
[2025-09-18 09:28:00] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/22/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.83s
[2025-09-18 09:28:00] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/47/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.85s
[2025-09-18 09:28:00] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/36/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.84s
[2025-09-18 09:28:00] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/46/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.83s
[2025-09-18 09:28:00] ✅ 测速成功: http://111.53.96.67:8081/live/1/index.m3u8
   速度: 208.98KB/s | 数据量: 0.2KB | 总耗时: 0.47s
[2025-09-18 09:28:00] ✅ 测速成功: http://124.88.144.73:1935/live/jiaoyu/playlist.m3u8?%E5%85%B3%E6%B3%A8%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7[%E6%99%B4%E5%9B%AD]
   速度: 0.74KB/s | 数据量: 0.2KB | 总耗时: 0.90s
[2025-09-18 09:28:00] ✅ 测速成功: http://111.53.96.67:8081/live/1/index.m3u8?%E5%85%B3%E6%B3%A8%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7[%E6%99%B4%E5%9B%AD]
   速度: 208.98KB/s | 数据量: 0.2KB | 总耗时: 0.47s
[2025-09-18 09:28:00] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/48/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.80s
[2025-09-18 09:28:00] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/34/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.83s
[2025-09-18 09:28:03] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.241:8000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.241:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08c50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:03] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.159:8000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.159:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:03] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.158:8000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.158:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:03] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.242:8000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.242:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08350>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:03] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.116:8000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.116:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:03] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.117:8000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.117:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09c50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:03] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.115:8000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.115:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:03] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.189:8000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.189:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09150>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:03] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.243:8000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.243:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09b50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:03] ✅ 测速成功: http://183.64.174.171:40123/ch1.m3u8?zzhongqd
   速度: 0.04KB/s | 数据量: 0.1KB | 总耗时: 3.91s
[2025-09-18 09:28:06] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.235:8000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.235:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:06] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.129:8008
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.129:8008 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08850>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:06] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.60:8084
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.60:8084 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a250>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:06] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.172:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.172:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a650>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:06] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.105:8092
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.105:8092 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0aa50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:06] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.173:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.173:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ae50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:06] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.130:8004
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.130:8004 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b250>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:06] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.174:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.174:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b650>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:06] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.61:8104
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.61:8104 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ba50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:06] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.175:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.175:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bb50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:09] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.62:8112
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.62:8112 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:09] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.63:8116
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.63:8116 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09b50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:09] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.152:8120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.152:8120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09150>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:09] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.64:8124
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.64:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:09] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.124:8128
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.124:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09c50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:09] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.65:8132
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.65:8132 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:09] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.153:8136
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.153:8136 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08350>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:09] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.184:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.184:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:09] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.151:8144
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.151:8144 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:09] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.132:8012
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.132:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:12] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.136:8032
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.136:8032 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4050>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:12] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.137:8036
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.137:8036 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4350>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:12] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.135:8028
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.135:8028 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4650>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:12] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.134:8020
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.134:8020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4950>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:12] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.142:8048
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.142:8048 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4b50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:12] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.211:8064
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.211:8064 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4e50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:12] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.141:1234
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.141:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:12] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.122:8160
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.122:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:12] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.209:8052
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.209:8052 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:12] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.148:8072
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.148:8072 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bb50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:15] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.210:8056
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.210:8056 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ba50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:15] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.138:8044
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.138:8044 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b650>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:15] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.240:8172
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.240:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b250>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:15] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.149:8076
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.149:8076 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ae50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:15] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.156:8148
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.156:8148 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0aa50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:15] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.123:8164
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.123:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a650>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:15] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.45:8304
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.45:8304 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a250>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:15] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.133:8016
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.133:8016 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08850>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:15] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.26:8108
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.26:8108 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4d50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:15] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.29:8288
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.29:8288 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4850>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:18] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.46:8124
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.46:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4450>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:18] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.42:8172
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.42:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5150>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:18] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.39:8300
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.39:8300 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b650>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:18] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.48:8160
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.48:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:18] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.27:8128
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.27:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:18] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.49:8188
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.49:8188 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:18] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.47:8164
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.47:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b050>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:18] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.41:8140
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.41:8140 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ab50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:18] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.44:8184
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.44:8184 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a450>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:18] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.43:8176
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.43:8176 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09250>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:21] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.155:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.155:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:21] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.143:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.143:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:21] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.144:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.144:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:21] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.236:2000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.236:2000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5450>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:21] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.249:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.249:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4550>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:21] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.250:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.250:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4c50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:21] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.95:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.95:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4950>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:21] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.100:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.100:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4050>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:21] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.238:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.238:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ab50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:21] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.102:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.102:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:24] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.213:4220
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.213:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bd50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:24] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.214:4220
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.214:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09b50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:24] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.215:4220
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.215:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09450>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:24] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.216:4220
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.216:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a350>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:24] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.217:4220
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.217:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08850>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:24] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.218:4220
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.218:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a250>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:24] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.219:4220
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.219:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a650>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:24] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.220:4220
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.220:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0aa50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:24] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.57:8152
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.57:8152 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ae50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:24] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.54:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.54:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:27] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.56:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.56:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4b50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:27] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.188:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.188:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:27] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.163:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.163:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5150>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:27] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.221:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.221:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4d50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:27] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.96:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.96:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a350>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:27] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.154:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.154:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bd50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:27] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.187:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.187:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bb50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:27] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.58:8156
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.58:8156 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08950>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:28] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.165:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.165:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b450>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:28] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.164:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.164:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ac50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:30] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.94:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.94:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a050>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:30] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.92:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.92:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08f50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:30] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.91:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.91:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09150>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:30] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.93:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.93:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09c50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:30] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.74:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.74:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:30] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.195:9024
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.195:9024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4850>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:30] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.194:9020
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.194:9020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4250>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:30] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.68:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.68:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4650>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:31] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.67:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.67:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4c50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:31] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.90:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.90:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5b50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:33] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.196:9012
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.196:9012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ac50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:33] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.69:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.69:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bb50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:33] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.199:9000
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.199:9000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a350>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:33] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.80:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.80:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:33] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.51:9252
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.51:9252 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0be50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:33] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.147:9268
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.147:9268 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:33] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.71:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.71:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b350>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:33] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.75:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.75:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b850>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:34] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.76:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.76:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ab50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:34] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.85:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.85:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:36] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.77:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.77:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09450>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:36] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.83:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.83:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5450>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:36] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.81:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.81:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4350>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:36] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.52:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.52:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4150>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:36] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.78:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.78:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4d50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:36] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.193:8012
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.193:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4b50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:37] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.79:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.79:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a350>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:37] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.87:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.87:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:37] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.86:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.86:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09b50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:37] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.73:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.73:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a650>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:39] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.72:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.72:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:39] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.89:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.89:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a850>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:39] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.82:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.82:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:39] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.70:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.70:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09c50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:39] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.84:4120
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.84:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09150>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:39] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.125:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.125:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08f50>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:40] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.126:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.126:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a050>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:40] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.127:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.127:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b250>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:40] ❌ 测速失败: http://114.254.34.51:8888/rtp/239.3.1.128:8001
   错误: HTTPConnectionPool(host='114.254.34.51', port=8888): Max retries exceeded with url: /rtp/239.3.1.128:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4750>, 'Connection to 114.254.34.51 timed out. (connect timeout=3.05)')) | 域名: 114.254.34.51
[2025-09-18 09:28:40] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.241:8000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.241:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4450>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:42] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.159:8000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.159:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4950>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:42] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.158:8000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.158:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4050>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:42] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.242:8000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.242:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:42] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.116:8000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.116:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a650>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:42] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.117:8000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.117:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:43] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.115:8000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.115:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a350>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:43] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.189:8000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.189:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bd50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:43] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.243:8000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.243:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:43] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.235:8000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.235:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:43] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.129:8008
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.129:8008 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ae50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:45] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.60:8084
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.60:8084 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bc50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:45] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.172:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.172:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a250>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:45] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.105:8092
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.105:8092 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bb50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:45] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.173:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.173:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a750>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:45] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.130:8004
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.130:8004 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5e50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:46] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.174:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.174:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4a50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:46] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.61:8104
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.61:8104 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e6050>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:46] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.175:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.175:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4150>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:46] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.62:8112
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.62:8112 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:46] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.63:8116
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.63:8116 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a350>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:48] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.152:8120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.152:8120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0be50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:48] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.64:8124
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.64:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ac50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:48] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.124:8128
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.124:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:48] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.65:8132
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.65:8132 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0af50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:49] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.153:8136
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.153:8136 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b650>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:49] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.184:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.184:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b050>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:49] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.151:8144
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.151:8144 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b450>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:49] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.132:8012
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.132:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a450>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:49] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.136:8032
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.136:8032 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09b50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:49] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.137:8036
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.137:8036 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a850>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:51] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.135:8028
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.135:8028 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4d50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:51] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.134:8020
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.134:8020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5a50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:51] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.142:8048
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.142:8048 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5b50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:52] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.211:8064
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.211:8064 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4950>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:52] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.141:1234
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.141:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b650>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:52] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.122:8160
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.122:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ac50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:52] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.209:8052
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.209:8052 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09c50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:52] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.148:8072
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.148:8072 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09150>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:52] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.210:8056
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.210:8056 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08950>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:52] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.138:8044
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.138:8044 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b250>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:55] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.240:8172
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.240:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09550>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:55] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.149:8076
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.149:8076 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0aa50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:55] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.156:8148
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.156:8148 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ab50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:55] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.123:8164
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.123:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b850>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:55] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.45:8304
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.45:8304 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:55] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.133:8016
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.133:8016 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:55] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.26:8108
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.26:8108 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4050>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:55] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.29:8288
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.29:8288 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4e50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:55] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.46:8124
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.46:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4350>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:55] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.42:8172
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.42:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e6050>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:58] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.39:8300
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.39:8300 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4650>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:58] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.27:8128
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.27:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09150>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:58] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.48:8160
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.48:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09550>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:58] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.49:8188
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.49:8188 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bd50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:58] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.47:8164
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.47:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a650>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:58] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.41:8140
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.41:8140 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a250>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:58] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.44:8184
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.44:8184 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09450>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:58] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.43:8176
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.43:8176 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:58] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.155:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.155:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a050>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:28:58] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.143:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.143:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08850>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:01] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.144:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.144:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:01] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.249:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.249:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0af50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:01] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.236:2000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.236:2000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0be50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:01] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.250:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.250:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4150>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:01] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.95:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.95:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5150>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:01] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.100:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.100:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4450>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:01] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.238:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.238:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5b50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:01] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.102:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.102:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:01] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.213:4220
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.213:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a650>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:01] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.214:4220
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.214:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:04] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.215:4220
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.215:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b750>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:04] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.216:4220
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.216:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a450>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:04] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.217:4220
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.217:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09250>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:04] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.218:4220
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.218:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a750>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:04] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.219:4220
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.219:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:04] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.220:4220
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.220:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:04] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.57:8152
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.57:8152 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b850>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:04] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.54:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.54:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ab50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:04] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.56:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.56:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4d50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:04] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.188:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.188:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4750>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:07] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.163:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.163:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4b50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:07] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.221:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.221:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5e50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:07] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.96:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.96:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4350>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:07] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.154:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.154:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a750>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:07] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.187:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.187:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b750>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:07] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.58:8156
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.58:8156 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b250>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:07] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.165:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.165:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09c50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:07] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.164:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.164:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b650>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:07] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.94:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.94:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ba50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:07] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.92:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.92:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a850>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:10] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.91:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.91:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08f50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:10] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.93:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.93:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b450>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:10] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.74:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.74:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b050>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:10] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.195:9024
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.195:9024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bd50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:10] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.194:9020
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.194:9020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09450>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:10] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.68:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.68:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e6050>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:10] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.67:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.67:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5450>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:10] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.90:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.90:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4950>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:10] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.196:9012
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.196:9012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4450>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:10] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.69:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.69:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a850>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:13] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.199:9000
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.199:9000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09c50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:13] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.80:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.80:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a250>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:13] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.51:9252
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.51:9252 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09550>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:13] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.147:9268
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.147:9268 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:13] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.71:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.71:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0be50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:13] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.75:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.75:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:13] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.76:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.76:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ae50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:13] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.85:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.85:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:13] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.77:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.77:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:13] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.83:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.83:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:16] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.81:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.81:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4150>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:16] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.78:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.78:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4a50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:16] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.52:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.52:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5a50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:16] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.193:8012
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.193:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4050>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:16] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.79:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.79:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4b50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:16] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.87:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.87:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5c50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:16] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.73:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.73:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09550>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:16] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.86:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.86:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:16] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.72:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.72:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09250>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:16] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.89:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.89:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:19] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.82:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.82:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08950>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:19] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.84:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.84:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a350>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:19] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.70:4120
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.70:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ab50>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:19] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.125:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.125:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08350>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:19] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.126:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.126:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08850>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:19] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.127:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.127:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a050>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:19] ❌ 测速失败: http://114.241.215.81:4022/rtp/239.3.1.128:8001
   错误: HTTPConnectionPool(host='114.241.215.81', port=4022): Max retries exceeded with url: /rtp/239.3.1.128:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b250>, 'Connection to 114.241.215.81 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.81
[2025-09-18 09:29:22] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.146:5140
   速度: 1083.80KB/s | 数据量: 6144.0KB | 总耗时: 6.21s
[2025-09-18 09:29:23] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.236:5140
   速度: 1087.18KB/s | 数据量: 6144.0KB | 总耗时: 6.22s
[2025-09-18 09:29:23] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.209:5140
   速度: 1075.93KB/s | 数据量: 6144.0KB | 总耗时: 6.28s
[2025-09-18 09:29:23] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.46:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.53s
[2025-09-18 09:29:23] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.9:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.40s
[2025-09-18 09:29:25] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.55:5140
   速度: 786.64KB/s | 数据量: 4096.0KB | 总耗时: 5.81s
[2025-09-18 09:29:25] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.237:5140
   速度: 1097.91KB/s | 数据量: 6144.0KB | 总耗时: 6.20s
[2025-09-18 09:29:25] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.136:5140
   速度: 1097.11KB/s | 数据量: 6144.0KB | 总耗时: 6.21s
[2025-09-18 09:29:25] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.196:5140
   速度: 1098.72KB/s | 数据量: 6144.0KB | 总耗时: 6.21s
[2025-09-18 09:29:25] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.134:5140
   速度: 1098.35KB/s | 数据量: 6144.0KB | 总耗时: 6.27s
[2025-09-18 09:29:26] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.210:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.96s
[2025-09-18 09:29:26] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.17:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.97s
[2025-09-18 09:29:26] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.131:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.21s
[2025-09-18 09:29:26] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.132:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.06s
[2025-09-18 09:29:26] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.13:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.03s
[2025-09-18 09:29:29] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.71:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:29] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.56:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-18 09:29:31] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.211:5140
   速度: 1083.38KB/s | 数据量: 6144.0KB | 总耗时: 6.23s
[2025-09-18 09:29:31] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.145:5140
   速度: 1096.50KB/s | 数据量: 6144.0KB | 总耗时: 6.18s
[2025-09-18 09:29:31] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.135:5140
   速度: 1093.86KB/s | 数据量: 6144.0KB | 总耗时: 6.21s
[2025-09-18 09:29:31] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.68:5140
   速度: 1107.61KB/s | 数据量: 6144.0KB | 总耗时: 6.10s
[2025-09-18 09:29:32] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.70:5140
   速度: 946.91KB/s | 数据量: 5120.0KB | 总耗时: 5.99s
[2025-09-18 09:29:32] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.2:5140
   速度: 755.59KB/s | 数据量: 4096.0KB | 总耗时: 6.00s
[2025-09-18 09:29:32] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.8:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-18 09:29:32] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.4:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-18 09:29:32] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.208:5140
   速度: 172.23KB/s | 数据量: 1024.0KB | 总耗时: 6.57s
[2025-09-18 09:29:32] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.69:5140
   速度: 1091.77KB/s | 数据量: 6144.0KB | 总耗时: 6.18s
[2025-09-18 09:29:34] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.196:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.56s
[2025-09-18 09:29:35] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.4:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:35] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.42:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:35] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.1:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.92s
[2025-09-18 09:29:35] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.107:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.82s
[2025-09-18 09:29:35] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.200:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.02s
[2025-09-18 09:29:38] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.10:5140
   速度: 1096.40KB/s | 数据量: 6144.0KB | 总耗时: 6.16s
[2025-09-18 09:29:38] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.23:5140
   速度: 1093.88KB/s | 数据量: 6144.0KB | 总耗时: 6.19s
[2025-09-18 09:29:38] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.178:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:38] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.177:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:38] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.198:5140
   速度: 354.11KB/s | 数据量: 2048.0KB | 总耗时: 6.43s
[2025-09-18 09:29:38] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.52:5140
   速度: 1091.49KB/s | 数据量: 6144.0KB | 总耗时: 6.18s
[2025-09-18 09:29:39] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.10:5140
   速度: 1621.73KB/s | 数据量: 8192.0KB | 总耗时: 5.64s
[2025-09-18 09:29:41] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.139:5140
   速度: 949.86KB/s | 数据量: 5120.0KB | 总耗时: 5.99s
[2025-09-18 09:29:41] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.230:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.83s
[2025-09-18 09:29:41] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.228:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.10s
[2025-09-18 09:29:41] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.124:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:41] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.120:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:41] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.238:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.86s
[2025-09-18 09:29:41] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.239:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.16s
[2025-09-18 09:29:41] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.229:5140
   速度: 692.50KB/s | 数据量: 4096.0KB | 总耗时: 6.51s
[2025-09-18 09:29:41] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.29:5140
   速度: 497.40KB/s | 数据量: 3072.0KB | 总耗时: 6.79s
[2025-09-18 09:29:44] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.81:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.04s
[2025-09-18 09:29:44] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.83:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.04s
[2025-09-18 09:29:45] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.121:5140
   速度: 1095.47KB/s | 数据量: 6144.0KB | 总耗时: 6.17s
[2025-09-18 09:29:47] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.80:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.95s
[2025-09-18 09:29:47] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.6:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.95s
[2025-09-18 09:29:47] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.231:5140
   速度: 1118.30KB/s | 数据量: 6144.0KB | 总耗时: 6.06s
[2025-09-18 09:29:47] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.44:5140
   速度: 1110.50KB/s | 数据量: 6144.0KB | 总耗时: 6.10s
[2025-09-18 09:29:47] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.3:5140
   速度: 1109.53KB/s | 数据量: 6144.0KB | 总耗时: 6.11s
[2025-09-18 09:29:47] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.5:5140
   速度: 1106.71KB/s | 数据量: 6144.0KB | 总耗时: 6.12s
[2025-09-18 09:29:48] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.84:5140
   速度: 505.43KB/s | 数据量: 3072.0KB | 总耗时: 6.64s
[2025-09-18 09:29:48] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.122:5140
   速度: 203.84KB/s | 数据量: 1024.0KB | 总耗时: 7.71s
[2025-09-18 09:29:48] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.4:5140
   速度: 476.96KB/s | 数据量: 3072.0KB | 总耗时: 7.00s
[2025-09-18 09:29:49] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.123:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.18s
[2025-09-18 09:29:50] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.232:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:50] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.213:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.88s
[2025-09-18 09:29:50] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.231:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.90s
[2025-09-18 09:29:53] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.82:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:53] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.117:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:53] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.229:5140
   速度: 353.60KB/s | 数据量: 2048.0KB | 总耗时: 6.44s
[2025-09-18 09:29:54] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.232:5140
   速度: 353.63KB/s | 数据量: 2048.0KB | 总耗时: 7.24s
[2025-09-18 09:29:55] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.4:5140
   速度: 1086.75KB/s | 数据量: 6144.0KB | 总耗时: 6.89s
[2025-09-18 09:29:55] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.234:5140
   速度: 355.27KB/s | 数据量: 2048.0KB | 总耗时: 6.40s
[2025-09-18 09:29:55] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.238:5140
   速度: 353.52KB/s | 数据量: 2048.0KB | 总耗时: 6.43s
[2025-09-18 09:29:55] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.3:5140
   速度: 1083.90KB/s | 数据量: 6144.0KB | 总耗时: 6.32s
[2025-09-18 09:29:56] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.230:5140
   速度: 353.57KB/s | 数据量: 2048.0KB | 总耗时: 8.80s
[2025-09-18 09:29:56] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.38:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:29:56] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.116:5140
   速度: 354.64KB/s | 数据量: 2048.0KB | 总耗时: 6.43s
[2025-09-18 09:29:57] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.0.8:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.64s
[2025-09-18 09:29:58] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.125:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.88s
[2025-09-18 09:29:58] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.14:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.96s
[2025-09-18 09:29:58] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.52:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.77s
[2025-09-18 09:29:58] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.50:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.68s
[2025-09-18 09:30:00] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.45:5140
   速度: 1004.02KB/s | 数据量: 5120.0KB | 总耗时: 6.73s
[2025-09-18 09:30:00] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.251:5140
   速度: 353.62KB/s | 数据量: 2048.0KB | 总耗时: 7.50s
[2025-09-18 09:30:02] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.185:5140
   速度: 191.93KB/s | 数据量: 1024.0KB | 总耗时: 6.10s
[2025-09-18 09:30:02] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.194:5140
   速度: 355.42KB/s | 数据量: 2048.0KB | 总耗时: 6.42s
[2025-09-18 09:30:03] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.1.48:5140
   速度: 355.00KB/s | 数据量: 2048.0KB | 总耗时: 6.41s
[2025-09-18 09:30:03] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.74:5140
   速度: 1099.08KB/s | 数据量: 6144.0KB | 总耗时: 6.16s
[2025-09-18 09:30:04] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.207:5140
   速度: 1097.59KB/s | 数据量: 6144.0KB | 总耗时: 6.15s
[2025-09-18 09:30:05] ✅ 测速成功: http://223.167.230.154:4022/rtp/239.45.3.75:5140
   速度: 1097.03KB/s | 数据量: 6144.0KB | 总耗时: 7.19s
[2025-09-18 09:30:09] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.146:5140
   速度: 97.00KB/s | 数据量: 1024.0KB | 总耗时: 11.07s
[2025-09-18 09:30:12] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.209:5140
   速度: 73.26KB/s | 数据量: 1024.0KB | 总耗时: 14.47s
[2025-09-18 09:30:14] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.236:5140
   速度: 72.52KB/s | 数据量: 1024.0KB | 总耗时: 14.65s
[2025-09-18 09:30:15] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.196:5140
   速度: 83.88KB/s | 数据量: 1024.0KB | 总耗时: 12.74s
[2025-09-18 09:30:15] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.55:5140
   速度: 84.76KB/s | 数据量: 1024.0KB | 总耗时: 12.63s
[2025-09-18 09:30:16] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.134:5140
   速度: 77.05KB/s | 数据量: 1024.0KB | 总耗时: 13.77s
[2025-09-18 09:30:19] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.131:5140
   速度: 108.82KB/s | 数据量: 1024.0KB | 总耗时: 9.91s
[2025-09-18 09:30:22] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.46:5140
   速度: 56.59KB/s | 数据量: 1024.0KB | 总耗时: 18.58s
[2025-09-18 09:30:27] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.17:5140
   速度: 90.15KB/s | 数据量: 1024.0KB | 总耗时: 11.87s
[2025-09-18 09:30:27] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.9:5140
   速度: 46.71KB/s | 数据量: 1024.0KB | 总耗时: 22.44s
[2025-09-18 09:30:30] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.132:5140
   速度: 59.90KB/s | 数据量: 1024.0KB | 总耗时: 17.60s
[2025-09-18 09:30:31] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.136:5140
   速度: 36.03KB/s | 数据量: 1024.0KB | 总耗时: 28.93s
[2025-09-18 09:30:33] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.135:5140
   速度: 75.09KB/s | 数据量: 1024.0KB | 总耗时: 14.12s
[2025-09-18 09:30:35] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.13:5140
   速度: 50.14KB/s | 数据量: 1024.0KB | 总耗时: 20.92s
[2025-09-18 09:30:36] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.145:5140
   速度: 80.93KB/s | 数据量: 1024.0KB | 总耗时: 13.18s
[2025-09-18 09:30:36] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.237:5140
   速度: 29.24KB/s | 数据量: 1024.0KB | 总耗时: 35.54s
[2025-09-18 09:30:38] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.208:5140
   速度: 94.58KB/s | 数据量: 1024.0KB | 总耗时: 11.37s
[2025-09-18 09:30:38] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.211:5140
   速度: 48.17KB/s | 数据量: 1024.0KB | 总耗时: 21.75s
[2025-09-18 09:30:42] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.210:5140
   速度: 38.74KB/s | 数据量: 1024.0KB | 总耗时: 26.96s
[2025-09-18 09:30:44] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.70:5140
   速度: 100.03KB/s | 数据量: 1024.0KB | 总耗时: 10.75s
[2025-09-18 09:30:47] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.196:5140
   速度: 121.30KB/s | 数据量: 1024.0KB | 总耗时: 8.98s
[2025-09-18 09:30:48] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.2:5140
   速度: 56.62KB/s | 数据量: 1024.0KB | 总耗时: 18.58s
[2025-09-18 09:30:51] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.68:5140
   速度: 43.97KB/s | 数据量: 1024.0KB | 总耗时: 23.79s
[2025-09-18 09:30:51] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.69:5140
   速度: 51.13KB/s | 数据量: 1024.0KB | 总耗时: 20.56s
[2025-09-18 09:30:52] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.71:5140
   速度: 63.00KB/s | 数据量: 1024.0KB | 总耗时: 16.75s
[2025-09-18 09:30:55] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.198:5140
   速度: 93.36KB/s | 数据量: 1024.0KB | 总耗时: 11.50s
[2025-09-18 09:30:55] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.4:5140
   速度: 54.39KB/s | 数据量: 1024.0KB | 总耗时: 19.32s
[2025-09-18 09:30:58] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.56:5140
   速度: 46.94KB/s | 数据量: 1024.0KB | 总耗时: 22.31s
[2025-09-18 09:30:58] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.200:5140
   速度: 114.29KB/s | 数据量: 1024.0KB | 总耗时: 9.49s
[2025-09-18 09:31:00] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.23:5140
   速度: 79.38KB/s | 数据量: 1024.0KB | 总耗时: 13.40s
[2025-09-18 09:31:01] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.10:5140
   速度: 58.02KB/s | 数据量: 1024.0KB | 总耗时: 18.13s
[2025-09-18 09:31:04] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.8:5140
   速度: 40.69KB/s | 数据量: 1024.0KB | 总耗时: 25.69s
[2025-09-18 09:31:10] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.10:5140
   速度: 90.10KB/s | 数据量: 1024.0KB | 总耗时: 11.89s
[2025-09-18 09:31:11] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.52:5140
   速度: 53.13KB/s | 数据量: 1024.0KB | 总耗时: 19.78s
[2025-09-18 09:31:11] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.139:5140
   速度: 79.97KB/s | 数据量: 1024.0KB | 总耗时: 13.32s
[2025-09-18 09:31:12] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.229:5140
   速度: 93.03KB/s | 数据量: 1024.0KB | 总耗时: 11.54s
[2025-09-18 09:31:14] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.1:5140
   速度: 54.82KB/s | 数据量: 1024.0KB | 总耗时: 19.22s
[2025-09-18 09:31:15] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.107:5140
   速度: 52.34KB/s | 数据量: 1024.0KB | 总耗时: 20.06s
[2025-09-18 09:31:18] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.29:5140
   速度: 60.06KB/s | 数据量: 1024.0KB | 总耗时: 17.55s
[2025-09-18 09:31:19] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.42:5140
   速度: 39.87KB/s | 数据量: 1024.0KB | 总耗时: 26.20s
[2025-09-18 09:31:23] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.177:5140
   速度: 55.19KB/s | 数据量: 1024.0KB | 总耗时: 19.05s
[2025-09-18 09:31:23] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.4:5140
   速度: 33.12KB/s | 数据量: 1024.0KB | 总耗时: 31.44s
[2025-09-18 09:31:24] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.239:5140
   速度: 82.48KB/s | 数据量: 1024.0KB | 总耗时: 12.92s
[2025-09-18 09:31:24] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.178:5140
   速度: 74.84KB/s | 数据量: 1024.0KB | 总耗时: 14.19s
[2025-09-18 09:31:29] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.120:5140
   速度: 71.82KB/s | 数据量: 1024.0KB | 总耗时: 14.79s
[2025-09-18 09:31:32] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.124:5140
   速度: 53.67KB/s | 数据量: 1024.0KB | 总耗时: 19.57s
[2025-09-18 09:31:32] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.228:5140
   速度: 50.05KB/s | 数据量: 1024.0KB | 总耗时: 20.98s
[2025-09-18 09:31:32] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.238:5140
   速度: 61.81KB/s | 数据量: 1024.0KB | 总耗时: 17.11s
[2025-09-18 09:31:33] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.230:5140
   速度: 72.16KB/s | 数据量: 1024.0KB | 总耗时: 14.70s
[2025-09-18 09:31:37] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.3:5140
   速度: 83.89KB/s | 数据量: 1024.0KB | 总耗时: 12.71s
[2025-09-18 09:31:39] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.83:5140
   速度: 159.04KB/s | 数据量: 1024.0KB | 总耗时: 6.95s
[2025-09-18 09:31:43] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.121:5140
   速度: 42.25KB/s | 数据量: 1024.0KB | 总耗时: 24.74s
[2025-09-18 09:31:43] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.5:5140
   速度: 50.67KB/s | 数据量: 1024.0KB | 总耗时: 20.71s
[2025-09-18 09:31:43] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.122:5140
   速度: 50.80KB/s | 数据量: 1024.0KB | 总耗时: 20.70s
[2025-09-18 09:31:44] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.44:5140
   速度: 52.44KB/s | 数据量: 1024.0KB | 总耗时: 20.07s
[2025-09-18 09:31:46] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.4:5140
   速度: 79.02KB/s | 数据量: 1024.0KB | 总耗时: 13.49s
[2025-09-18 09:31:48] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.81:5140
   速度: 55.10KB/s | 数据量: 1024.0KB | 总耗时: 19.10s
[2025-09-18 09:31:52] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.123:5140
   速度: 124.29KB/s | 数据量: 1024.0KB | 总耗时: 8.73s
[2025-09-18 09:31:53] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.6:5140
   速度: 77.39KB/s | 数据量: 1024.0KB | 总耗时: 13.76s
[2025-09-18 09:31:55] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.80:5140
   速度: 58.36KB/s | 数据量: 1024.0KB | 总耗时: 18.07s
[2025-09-18 09:31:59] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.213:5140
   速度: 103.71KB/s | 数据量: 1024.0KB | 总耗时: 10.39s
[2025-09-18 09:31:59] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.84:5140
   速度: 39.21KB/s | 数据量: 1024.0KB | 总耗时: 26.63s
[2025-09-18 09:32:03] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.231:5140
   速度: 32.88KB/s | 数据量: 1024.0KB | 总耗时: 31.64s
[2025-09-18 09:32:03] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.231:5140
   速度: 60.98KB/s | 数据量: 1024.0KB | 总耗时: 17.28s
[2025-09-18 09:32:06] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.232:5140
   速度: 47.32KB/s | 数据量: 1024.0KB | 总耗时: 22.15s
[2025-09-18 09:32:07] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.230:5140
   速度: 45.20KB/s | 数据量: 1024.0KB | 总耗时: 23.20s
[2025-09-18 09:32:10] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.229:5140
   速度: 39.90KB/s | 数据量: 1024.0KB | 总耗时: 26.18s
[2025-09-18 09:32:10] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.4:5140
   速度: 60.74KB/s | 数据量: 1024.0KB | 总耗时: 17.36s
[2025-09-18 09:32:11] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.3:5140
   速度: 85.35KB/s | 数据量: 1024.0KB | 总耗时: 12.53s
[2025-09-18 09:32:15] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.238:5140
   速度: 126.49KB/s | 数据量: 2048.0KB | 总耗时: 16.69s
[2025-09-18 09:32:17] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.82:5140
   速度: 90.05KB/s | 数据量: 1024.0KB | 总耗时: 11.88s
[2025-09-18 09:32:18] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.232:5140
   速度: 40.14KB/s | 数据量: 1024.0KB | 总耗时: 26.06s
[2025-09-18 09:32:21] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.234:5140
   速度: 40.30KB/s | 数据量: 1024.0KB | 总耗时: 25.95s
[2025-09-18 09:32:21] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.117:5140
   速度: 61.05KB/s | 数据量: 1024.0KB | 总耗时: 17.29s
[2025-09-18 09:32:25] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.45:5140
   速度: 73.39KB/s | 数据量: 1024.0KB | 总耗时: 14.49s
[2025-09-18 09:32:26] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.116:5140
   速度: 46.88KB/s | 数据量: 1024.0KB | 总耗时: 22.34s
[2025-09-18 09:32:28] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.251:5140
   速度: 50.03KB/s | 数据量: 1024.0KB | 总耗时: 20.98s
[2025-09-18 09:32:28] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.38:5140
   速度: 56.11KB/s | 数据量: 1024.0KB | 总耗时: 18.74s
[2025-09-18 09:32:29] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.0.8:5140
   速度: 60.02KB/s | 数据量: 1024.0KB | 总耗时: 17.57s
[2025-09-18 09:32:30] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.52:5140
   速度: 88.31KB/s | 数据量: 1024.0KB | 总耗时: 12.13s
[2025-09-18 09:32:36] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.111:5002
   速度: 1222.75KB/s | 数据量: 6144.0KB | 总耗时: 5.62s
[2025-09-18 09:32:37] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.207:5140
   速度: 141.33KB/s | 数据量: 1024.0KB | 总耗时: 7.78s
[2025-09-18 09:32:37] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.14:5140
   速度: 47.31KB/s | 数据量: 1024.0KB | 总耗时: 22.15s
[2025-09-18 09:32:38] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.125:5140
   速度: 51.29KB/s | 数据量: 1024.0KB | 总耗时: 20.49s
[2025-09-18 09:32:38] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.185:5140
   速度: 79.15KB/s | 数据量: 1024.0KB | 总耗时: 13.44s
[2025-09-18 09:32:39] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.50:5140
   速度: 58.42KB/s | 数据量: 1024.0KB | 总耗时: 18.02s
[2025-09-18 09:32:40] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.194:5140
   速度: 54.87KB/s | 数据量: 1024.0KB | 总耗时: 19.20s
[2025-09-18 09:32:40] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.1.48:5140
   速度: 73.24KB/s | 数据量: 1024.0KB | 总耗时: 14.49s
[2025-09-18 09:32:40] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.74:5140
   速度: 88.13KB/s | 数据量: 1024.0KB | 总耗时: 12.15s
[2025-09-18 09:32:41] ✅ 测速成功: http://180.165.1.43:9898/rtp/239.45.3.75:5140
   速度: 87.00KB/s | 数据量: 1024.0KB | 总耗时: 12.29s
[2025-09-18 09:32:41] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.130:5002
   速度: 1216.64KB/s | 数据量: 6144.0KB | 总耗时: 5.64s
[2025-09-18 09:32:43] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.131:5002
   速度: 1173.58KB/s | 数据量: 6144.0KB | 总耗时: 5.88s
[2025-09-18 09:32:43] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.123:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.59s
[2025-09-18 09:32:43] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.120:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.54s
[2025-09-18 09:32:43] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.149:5002
   速度: 1192.20KB/s | 数据量: 6144.0KB | 总耗时: 5.78s
[2025-09-18 09:32:44] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.128:5002
   速度: 1192.40KB/s | 数据量: 6144.0KB | 总耗时: 5.82s
[2025-09-18 09:32:44] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.129:5002
   速度: 599.17KB/s | 数据量: 3072.0KB | 总耗时: 5.77s
[2025-09-18 09:32:45] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.158:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.26s
[2025-09-18 09:32:46] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.151:5002
   速度: 1174.20KB/s | 数据量: 6144.0KB | 总耗时: 5.88s
[2025-09-18 09:32:47] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.122:5002
   速度: 390.00KB/s | 数据量: 3072.0KB | 总耗时: 8.48s
[2025-09-18 09:32:47] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.195:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.57s
[2025-09-18 09:32:48] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.196:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.39s
[2025-09-18 09:32:49] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.133:5002
   速度: 281.14KB/s | 数据量: 2048.0KB | 总耗时: 8.00s
[2025-09-18 09:32:49] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.121:5002
   速度: 198.58KB/s | 数据量: 1024.0KB | 总耗时: 6.40s
[2025-09-18 09:32:50] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.192:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.12s
[2025-09-18 09:32:50] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.142:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-18 09:32:50] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.138:5002
   速度: 1149.04KB/s | 数据量: 6144.0KB | 总耗时: 6.65s
[2025-09-18 09:32:50] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.150:5002
   速度: 286.08KB/s | 数据量: 2048.0KB | 总耗时: 7.87s
[2025-09-18 09:32:51] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.160:5002
   速度: 294.83KB/s | 数据量: 2048.0KB | 总耗时: 8.22s
[2025-09-18 09:32:51] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.119:5002
   速度: 1148.10KB/s | 数据量: 6144.0KB | 总耗时: 6.61s
[2025-09-18 09:32:52] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.144:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.11s
[2025-09-18 09:32:52] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.140:5002
   速度: 792.76KB/s | 数据量: 4096.0KB | 总耗时: 6.42s
[2025-09-18 09:32:53] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.237:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:32:53] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.52:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:32:54] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.214:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.26s
[2025-09-18 09:32:54] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.213:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.77s
[2025-09-18 09:32:54] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.193:5002
   速度: 1133.28KB/s | 数据量: 6144.0KB | 总耗时: 6.08s
[2025-09-18 09:32:55] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.194:5002
   速度: 802.20KB/s | 数据量: 4096.0KB | 总耗时: 6.04s
[2025-09-18 09:32:56] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.176:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:32:56] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.215:5002
   速度: 809.56KB/s | 数据量: 4096.0KB | 总耗时: 5.76s
[2025-09-18 09:32:57] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.169:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:32:57] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.166:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.93s
[2025-09-18 09:32:57] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.172:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-18 09:32:57] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.175:5002
   速度: 1131.42KB/s | 数据量: 6144.0KB | 总耗时: 6.12s
[2025-09-18 09:32:58] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.173:5002
   速度: 1130.65KB/s | 数据量: 6144.0KB | 总耗时: 6.10s
[2025-09-18 09:32:59] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.174:5002
   速度: 531.57KB/s | 数据量: 3072.0KB | 总耗时: 6.39s
[2025-09-18 09:32:59] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.170:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.58s
[2025-09-18 09:32:59] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.168:5002
   速度: 521.84KB/s | 数据量: 3072.0KB | 总耗时: 6.54s
[2025-09-18 09:33:00] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.127:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:00] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.113:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-18 09:33:01] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.31:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.89s
[2025-09-18 09:33:01] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.171:5002
   速度: 1080.24KB/s | 数据量: 6144.0KB | 总耗时: 6.32s
[2025-09-18 09:33:02] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.81:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-18 09:33:02] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.177:5002
   速度: 1108.97KB/s | 数据量: 6144.0KB | 总耗时: 6.17s
[2025-09-18 09:33:03] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.26:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:03] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.167:5002
   速度: 1099.40KB/s | 数据量: 6144.0KB | 总耗时: 6.25s
[2025-09-18 09:33:04] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.112:5002
   速度: 1110.18KB/s | 数据量: 6144.0KB | 总耗时: 6.19s
[2025-09-18 09:33:04] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.126:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:05] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.123:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.23s
[2025-09-18 09:33:05] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.155:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-18 09:33:05] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.147:5002
   速度: 608.81KB/s | 数据量: 3072.0KB | 总耗时: 5.73s
[2025-09-18 09:33:06] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.116:5002
   速度: 434.37KB/s | 数据量: 3072.0KB | 总耗时: 7.67s
[2025-09-18 09:33:06] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.114:5002
   速度: 510.35KB/s | 数据量: 3072.0KB | 总耗时: 6.65s
[2025-09-18 09:33:07] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.28:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.08s
[2025-09-18 09:33:08] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.27:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-18 09:33:08] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.61:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:09] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.29:5002
   速度: 1125.59KB/s | 数据量: 6144.0KB | 总耗时: 6.65s
[2025-09-18 09:33:09] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.154:5002
   速度: 1119.44KB/s | 数据量: 6144.0KB | 总耗时: 6.58s
[2025-09-18 09:33:10] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.117:5002
   速度: 1120.00KB/s | 数据量: 6144.0KB | 总耗时: 6.59s
[2025-09-18 09:33:10] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.56:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.35s
[2025-09-18 09:33:10] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.32:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.44s
[2025-09-18 09:33:10] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.54:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:10] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.82:5002
   速度: 1125.25KB/s | 数据量: 6144.0KB | 总耗时: 6.73s
[2025-09-18 09:33:12] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.115:5002
   速度: 1145.42KB/s | 数据量: 6144.0KB | 总耗时: 6.58s
[2025-09-18 09:33:12] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.30:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.18s
[2025-09-18 09:33:13] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.51:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.16s
[2025-09-18 09:33:13] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.57:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:13] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.181:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:13] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.35:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:15] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.41:5002
   速度: 336.09KB/s | 数据量: 2048.0KB | 总耗时: 6.84s
[2025-09-18 09:33:15] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.50:5002
   速度: 330.47KB/s | 数据量: 2048.0KB | 总耗时: 6.94s
[2025-09-18 09:33:15] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.236:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:16] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.146:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:16] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.141:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-18 09:33:16] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.61:5002
   速度: 330.48KB/s | 数据量: 2048.0KB | 总耗时: 6.95s
[2025-09-18 09:33:17] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.118:5002
   速度: 335.41KB/s | 数据量: 2048.0KB | 总耗时: 6.87s
[2025-09-18 09:33:18] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.124:5002
   速度: 1132.07KB/s | 数据量: 6144.0KB | 总耗时: 6.09s
[2025-09-18 09:33:18] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.139:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.16s
[2025-09-18 09:33:18] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.237:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.06s
[2025-09-18 09:33:18] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.143:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:19] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.134:5002
   速度: 1123.73KB/s | 数据量: 6144.0KB | 总耗时: 6.12s
[2025-09-18 09:33:19] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.19:5002
   速度: 1069.74KB/s | 数据量: 6144.0KB | 总耗时: 6.41s
[2025-09-18 09:33:21] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.57:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:21] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.105:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:21] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.104:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.06s
[2025-09-18 09:33:21] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.129:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-18 09:33:21] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.145:5002
   速度: 402.86KB/s | 数据量: 2048.0KB | 总耗时: 5.74s
[2025-09-18 09:33:22] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.207:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.59s
[2025-09-18 09:33:22] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.137:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.87s
[2025-09-18 09:33:22] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.135:5002
   速度: 1119.62KB/s | 数据量: 6144.0KB | 总耗时: 6.15s
[2025-09-18 09:33:23] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.247:5002
   速度: 333.39KB/s | 数据量: 2048.0KB | 总耗时: 6.78s
[2025-09-18 09:33:23] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.236:5002
   速度: 1127.01KB/s | 数据量: 6144.0KB | 总耗时: 6.06s
[2025-09-18 09:33:24] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.82:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:24] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.55:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:25] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.4:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:25] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.7:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:25] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.8:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.85s
[2025-09-18 09:33:27] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.62:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-18 09:33:28] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.27:5002
   速度: 330.13KB/s | 数据量: 2048.0KB | 总耗时: 6.94s
[2025-09-18 09:33:28] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.205:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:28] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.216:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:28] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.171:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:28] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.110:5002
   速度: 309.58KB/s | 数据量: 2048.0KB | 总耗时: 7.35s
[2025-09-18 09:33:29] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.2:5002
   速度: 309.89KB/s | 数据量: 2048.0KB | 总耗时: 7.37s
[2025-09-18 09:33:30] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.2.14:5002
   速度: 1108.17KB/s | 数据量: 6144.0KB | 总耗时: 6.17s
[2025-09-18 09:33:30] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.83:5002
   速度: 309.09KB/s | 数据量: 2048.0KB | 总耗时: 7.38s
[2025-09-18 09:33:31] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.58:5002
   速度: 336.29KB/s | 数据量: 2048.0KB | 总耗时: 6.84s
[2025-09-18 09:33:31] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.177:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.64s
[2025-09-18 09:33:31] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.176:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:31] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.175:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-18 09:33:31] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.173:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.06s
[2025-09-18 09:33:31] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.174:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-18 09:33:34] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.126:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.126:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bc50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:34] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.172:5002
   速度: 330.56KB/s | 数据量: 2048.0KB | 总耗时: 6.92s
[2025-09-18 09:33:34] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.154:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.154:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09b50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:34] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.25:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.25:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09450>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:34] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.150:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.150:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b850>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:34] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.164:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.164:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a350>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:34] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.241:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.241:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09250>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:36] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.178:5002
   速度: 330.87KB/s | 数据量: 2048.0KB | 总耗时: 7.12s
[2025-09-18 09:33:36] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.179:5002
   速度: 330.90KB/s | 数据量: 2048.0KB | 总耗时: 6.90s
[2025-09-18 09:33:37] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.151:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.151:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b450>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:37] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.168:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.168:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ac50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:37] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.156:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.156:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:37] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.165:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.165:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:37] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.27:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.27:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:37] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.135:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.135:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4950>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:37] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.170:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.170:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4650>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:37] ✅ 测速成功: http://111.162.205.19:8686/rtp/225.1.1.180:5002
   速度: 337.10KB/s | 数据量: 2048.0KB | 总耗时: 6.84s
[2025-09-18 09:33:39] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.201:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.201:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08f50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:40] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.171:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.171:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09150>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:40] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.93:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.93:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5150>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:40] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.172:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.172:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4e50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:40] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.136:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.136:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4d50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:40] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.137:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.137:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5550>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:40] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.138:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.138:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5350>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:40] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.173:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.173:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5a50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:40] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.178:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.178:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e6150>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:40] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.139:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.139:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ba50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:42] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.15:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.15:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08f50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:43] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.140:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.140:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:43] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.179:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.179:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09250>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:43] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.182:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.182:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:43] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.230:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.230:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09c50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:43] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.45:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.45:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bb50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:43] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.29:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.29:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0af50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:43] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.38:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.38:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a850>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:43] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.52:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.52:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a750>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:43] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.47:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.47:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09550>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:45] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.60:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.60:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:46] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.56:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.56:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08950>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:46] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.63:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.63:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4650>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:46] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.58:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.58:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4950>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:46] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.51:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.51:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4150>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:46] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.125:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.125:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09c50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:46] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.206:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.206:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5c50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:46] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.122:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.122:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:46] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.117:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.117:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bb50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:46] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.123:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.123:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:48] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.116:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.116:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b650>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:49] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.141:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.141:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b750>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:49] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.115:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.115:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b250>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:49] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.181:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.181:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a650>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:49] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.131:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.131:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09450>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:49] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.186:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.186:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5950>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:49] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.130:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.130:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4550>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:49] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.124:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.124:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ac50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:49] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.185:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.185:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:49] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.74:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.74:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5650>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:51] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.110:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.110:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5050>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:52] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.26:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.26:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e6150>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:52] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.95:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.95:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b250>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:52] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.82:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.82:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:52] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.49:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.49:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:52] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.35:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.35:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b050>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:52] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.40:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.40:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09b50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:52] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.80:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.80:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b450>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:52] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.101:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.101:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b850>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:53] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.111:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.111:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ba50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:54] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.34:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.34:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08f50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:55] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.180:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.180:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:55] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.76:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.76:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a850>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:55] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.86:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.86:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ae50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:55] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.18:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.18:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5550>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:55] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.114:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.114:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5c50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:55] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.50:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.50:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e6250>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:55] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.160:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.160:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4a50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:55] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.212:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.212:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4650>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:56] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.238:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.238:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b850>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:57] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.239:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.239:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b050>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:58] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.169:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.169:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09750>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:58] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.67:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.67:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b250>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:58] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.161:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.161:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09550>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:58] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.90:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.90:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:58] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.163:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.163:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08850>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:58] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.162:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.162:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ac50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:58] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.107:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.107:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09c50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:58] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.98:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.98:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:33:59] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.108:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.108:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bb50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:00] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.127:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.127:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b750>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:01] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.128:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.128:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e6350>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:01] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.133:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.133:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4f50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:01] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.134:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.134:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e6150>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:01] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.149:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.149:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4550>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:01] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.53:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.53:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09550>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:01] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.59:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.59:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:01] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.198:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.198:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b850>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:01] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.188:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.188:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b050>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:02] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.28:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.28:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09150>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:03] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.6:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.6:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a450>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:04] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.43:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.43:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a050>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:04] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.8:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.8:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08350>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:04] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.103:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.103:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a750>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:04] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.159:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.159:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0ab50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:04] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.157:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.157:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab08d50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:04] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.57:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.57:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09b50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:04] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.104:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.104:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e5650>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:04] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.105:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.105:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4b50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:05] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.109:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.109:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4150>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:06] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.102:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.102:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1a9e4650>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:07] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.213:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.213:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a050>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:07] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.148:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.148:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b050>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:07] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.118:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.118:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b450>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:07] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.119:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.119:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0aa50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:07] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.197:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.197:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0bc50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:07] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.203:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.203:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:07] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.187:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.187:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a850>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:07] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.48:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.48:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0a350>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:07] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e4a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e5250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0009_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0009_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e5550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0003_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0003_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e4450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0016_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0016_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e6150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0011_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0011_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0aa50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0010_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0010_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0a850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0012_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0012_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0a050>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0013_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0013_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0a650>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.155:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.155:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0be50>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0014_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0014_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0bb50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0015_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0015_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0bd50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0119_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0119_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab09550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1000_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1000_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0ae50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0107_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0107_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0ab50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0122_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0122_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab09d50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0116_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0116_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab09150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0123_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0123_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e5450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0135_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0135_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e4550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0118_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0118_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e6250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0130_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0130_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e5350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0110_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0110_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e4150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0127_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0127_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e5d50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1034_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1034_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab09550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0124_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0124_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0be50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0126_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0126_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab08350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0132_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0132_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0a750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0121_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0121_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0af50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0142_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0142_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab09250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0136_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0136_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0b750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:08] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/0143_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/0143_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1011_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1011_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0b050>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1010_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1010_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0bc50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1008_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1008_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e4b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1005_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1005_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e4950>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1001_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1001_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e5850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1006_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1006_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab08e50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1007_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1007_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e6350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1004_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1004_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1a9e4a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1002_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1002_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab09a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1013_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1013_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab0af50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:09] ❌ 测速失败: http://42.231.44.185:9901/tsfile/live/1014_1.m3u8?key=txiptv&playlive=1&authid=0
   错误: HTTPConnectionPool(host='42.231.44.185', port=9901): Max retries exceeded with url: /tsfile/live/1014_1.m3u8?key=txiptv&playlive=1&authid=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff1ab09f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 42.231.44.185
[2025-09-18 09:34:10] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.214:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.214:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b650>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
[2025-09-18 09:34:10] ❌ 测速失败: http://116.2.173.67:4010/rtp/232.0.0.215:1234
   错误: HTTPConnectionPool(host='116.2.173.67', port=4010): Max retries exceeded with url: /rtp/232.0.0.215:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff1ab0b250>, 'Connection to 116.2.173.67 timed out. (connect timeout=3.05)')) | 域名: 116.2.173.67
