测速日志 2025-09-09 09:39:15
[2025-09-09 09:39:18] ✅ 测速成功: http://61.221.215.25:8800/hls/43/index.m3u8
   速度: 236.33KB/s | 数据量: 0.2KB | 总耗时: 0.28s
[2025-09-09 09:39:18] ✅ 测速成功: http://8.138.7.223/tv/cctv7.m3u8
   速度: 132.81KB/s | 数据量: 0.1KB | 总耗时: 0.37s
[2025-09-09 09:39:18] ✅ 测速成功: http://8.138.7.223/【公众号：榴芒电视】/cctv7.m3u8
   速度: 209.96KB/s | 数据量: 0.2KB | 总耗时: 0.38s
[2025-09-09 09:39:18] ✅ 测速成功: http://8.138.7.223/【公众号：榴芒电视】/cctv1.m3u8
   速度: 108.40KB/s | 数据量: 0.1KB | 总耗时: 0.38s
[2025-09-09 09:39:18] ✅ 测速成功: http://61.162.52.6:8088/newlive/live/hls/60/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.40s
[2025-09-09 09:39:18] ✅ 测速成功: http://123.146.162.24:8013/tslslive/PU2vzMI/hls/live_sd.m3u8?zzhongqd
   速度: 545.90KB/s | 数据量: 0.5KB | 总耗时: 0.40s
[2025-09-09 09:39:18] ✅ 测速成功: http://123.146.162.24:8017/c2F0hmi/1000/live.m3u8
   速度: 438.48KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:39:18] ✅ 测速成功: http://120.198.95.220:9901/tsfile/live/1038_1.m3u8?key=txiptv
   速度: 658.20KB/s | 数据量: 0.7KB | 总耗时: 0.42s
[2025-09-09 09:39:18] ✅ 测速成功: http://120.198.95.220:9901/tsfile/live/1071_1.m3u8?key=txiptv
   速度: 658.20KB/s | 数据量: 0.7KB | 总耗时: 0.42s
[2025-09-09 09:39:18] ✅ 测速成功: http://60.222.246.220:19433/hls1.m3u8
   速度: 0.91KB/s | 数据量: 0.2KB | 总耗时: 0.65s
[2025-09-09 09:39:18] ✅ 测速成功: http://112.27.235.94:8000/hls/18/index.m3u8
   速度: 240.23KB/s | 数据量: 0.2KB | 总耗时: 0.31s
[2025-09-09 09:39:18] ✅ 测速成功: http://8.138.7.223/【公众号：榴芒电视】/农林卫视.m3u8
   速度: 118.16KB/s | 数据量: 0.1KB | 总耗时: 0.38s
[2025-09-09 09:39:18] ✅ 测速成功: http://171.221.250.130:18888/27e684978eb642eeb90ab815f6cc51bf/c41893de5e8645b3b43aef1640859b0d.m3u8?zsicd,
   速度: 2.06KB/s | 数据量: 0.4KB | 总耗时: 0.64s
[2025-09-09 09:39:18] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/33/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.80s
[2025-09-09 09:39:18] ✅ 测速成功: http://124.88.144.73:1935/live/jiaoyu/playlist.m3u8
   速度: 0.58KB/s | 数据量: 0.1KB | 总耗时: 0.71s
[2025-09-09 09:39:18] ✅ 测速成功: http://112.27.235.94:8000/hls/24/index.m3u8
   速度: 240.23KB/s | 数据量: 0.2KB | 总耗时: 0.31s
[2025-09-09 09:39:18] ✅ 测速成功: http://124.88.144.73:1935/live/dywt/playlist.m3u8?zxinjd
   速度: 0.61KB/s | 数据量: 0.1KB | 总耗时: 0.70s
[2025-09-09 09:39:19] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/24/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.81s
[2025-09-09 09:39:19] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/45/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.81s
[2025-09-09 09:39:19] ✅ 测速成功: http://222.128.55.152:9080/live/dwq.m3u8
   速度: 0.44KB/s | 数据量: 0.1KB | 总耗时: 0.60s
[2025-09-09 09:39:19] ✅ 测速成功: http://112.27.235.94:8000/hls/25/index.m3u8
   速度: 240.23KB/s | 数据量: 0.2KB | 总耗时: 0.31s
[2025-09-09 09:39:19] ✅ 测速成功: http://124.88.144.73:1935/live/xwzh/playlist.m3u8?zxinjd
   速度: 0.25KB/s | 数据量: 0.1KB | 总耗时: 1.05s
[2025-09-09 09:39:19] ✅ 测速成功: http://112.132.10.54:9901/tsfile/live/1011_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:39:19] ✅ 测速成功: http://116.77.33.98:44330/tsfile/live/1004_1.m3u8?key=txiptv&playlive=0&authid=0
   速度: 818.36KB/s | 数据量: 0.8KB | 总耗时: 0.38s
[2025-09-09 09:39:19] ✅ 测速成功: http://8.138.7.223/tv/gzjs.m3u8
   速度: 133.79KB/s | 数据量: 0.1KB | 总耗时: 0.38s
[2025-09-09 09:39:19] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/49/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.85s
[2025-09-09 09:39:19] ✅ 测速成功: http://111.202.12.159:8080/kYGHWzA/1000/live.m3u8
   速度: 330.08KB/s | 数据量: 0.3KB | 总耗时: 0.41s
[2025-09-09 09:39:19] ✅ 测速成功: http://111.202.12.159:8080/3zvkK28/1000/live.m3u8
   速度: 69.34KB/s | 数据量: 0.1KB | 总耗时: 0.40s
[2025-09-09 09:39:19] ✅ 测速成功: http://124.88.144.73:1935/live/dywt/playlist.m3u8
   速度: 0.60KB/s | 数据量: 0.1KB | 总耗时: 0.69s
[2025-09-09 09:39:19] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/38/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.81s
[2025-09-09 09:39:19] ✅ 测速成功: http://116.128.242.83:9901/tsfile/live/1002_1.m3u8
   速度: 433.59KB/s | 数据量: 0.4KB | 总耗时: 0.45s
[2025-09-09 09:39:20] ✅ 测速成功: http://124.88.144.73:1935/live/jiaoyu/playlist.m3u8?%E5%85%B3%E6%B3%A8%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7[%E6%99%B4%E5%9B%AD]
   速度: 0.95KB/s | 数据量: 0.2KB | 总耗时: 0.71s
[2025-09-09 09:39:20] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/47/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.81s
[2025-09-09 09:39:20] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/22/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.77s
[2025-09-09 09:39:20] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/36/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.79s
[2025-09-09 09:39:20] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/46/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.80s
[2025-09-09 09:39:20] ✅ 测速成功: http://111.53.96.67:8081/live/1/index.m3u8
   速度: 208.98KB/s | 数据量: 0.2KB | 总耗时: 0.36s
[2025-09-09 09:39:20] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/48/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.78s
[2025-09-09 09:39:20] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/34/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.80s
[2025-09-09 09:39:20] ✅ 测速成功: http://111.53.96.67:8081/live/1/index.m3u8?%E5%85%B3%E6%B3%A8%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7[%E6%99%B4%E5%9B%AD]
   速度: 208.98KB/s | 数据量: 0.2KB | 总耗时: 0.35s
[2025-09-09 09:39:20] ✅ 测速成功: http://183.64.174.171:40123/ch1.m3u8?zzhongqd
   速度: 0.51KB/s | 数据量: 0.1KB | 总耗时: 0.69s
[2025-09-09 09:39:23] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.241:8000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.241:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041150>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:23] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.159:8000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.159:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041a50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:23] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.158:8000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.158:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040350>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:23] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.242:8000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.242:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040e50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:23] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.116:8000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.116:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040950>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:23] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.117:8000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.117:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041c50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:23] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.115:8000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.115:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041950>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:23] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.189:8000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.189:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041250>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:23] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.243:8000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.243:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040c50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:23] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.235:8000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.235:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041750>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:26] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.129:8008
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.129:8008 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041550>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:26] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.60:8084
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.60:8084 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041e50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:26] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.172:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.172:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042250>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:26] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.105:8092
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.105:8092 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042050>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:26] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.173:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.173:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040f50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:26] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.130:8004
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.130:8004 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042650>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:26] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.174:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.174:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042a50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:26] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.61:8104
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.61:8104 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042d50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:26] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.175:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.175:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043150>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:26] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.62:8112
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.62:8112 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043550>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:29] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.63:8116
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.63:8116 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043850>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:29] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.152:8120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.152:8120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043b50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:29] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.64:8124
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.64:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043e50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:29] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.124:8128
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.124:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc250>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:29] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.65:8132
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.65:8132 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc550>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:29] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.153:8136
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.153:8136 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc850>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:29] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.184:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.184:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdccb50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:29] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.151:8144
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.151:8144 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcce50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:29] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.132:8012
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.132:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042d50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:29] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.136:8032
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.136:8032 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040f50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:32] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.137:8036
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.137:8036 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043d50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:32] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.135:8028
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.135:8028 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043a50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:32] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.134:8020
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.134:8020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043750>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:32] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.142:8048
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.142:8048 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043350>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:32] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.211:8064
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.211:8064 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042f50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:32] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.141:1234
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.141:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042450>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:32] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.122:8160
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.122:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042850>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:32] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.209:8052
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.209:8052 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041b50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:32] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.148:8072
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.148:8072 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041a50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:32] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.210:8056
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.210:8056 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdccc50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:35] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.138:8044
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.138:8044 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc750>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:35] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.240:8172
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.240:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc350>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:35] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.149:8076
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.149:8076 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd150>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:35] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.156:8148
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.156:8148 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd450>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:35] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.123:8164
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.123:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043350>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:35] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.45:8304
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.45:8304 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043d50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:35] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.133:8016
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.133:8016 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042d50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:35] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.26:8108
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.26:8108 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041c50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:35] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.29:8288
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.29:8288 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042b50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:35] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.46:8124
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.46:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040c50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:38] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.42:8172
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.42:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043650>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:38] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.39:8300
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.39:8300 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043950>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:38] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.48:8160
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.48:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043c50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:38] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.27:8128
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.27:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042050>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:38] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.49:8188
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.49:8188 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042a50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:38] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.47:8164
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.47:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc050>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:38] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.41:8140
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.41:8140 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc650>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:38] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.44:8184
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.44:8184 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdccd50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:38] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.43:8176
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.43:8176 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc850>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:38] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.155:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.155:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd750>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:41] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.143:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.143:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040c50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:41] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.144:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.144:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042d50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:41] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.236:2000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.236:2000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042650>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:41] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.249:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.249:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043850>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:41] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.250:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.250:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041550>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:41] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.95:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.95:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043250>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:41] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.100:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.100:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041a50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:41] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.238:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.238:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041b50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:41] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.102:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.102:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042850>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:41] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.213:4220
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.213:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042450>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:44] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.214:4220
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.214:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcda50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:44] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.215:4220
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.215:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdccb50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:44] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.216:4220
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.216:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc950>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:44] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.217:4220
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.217:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd250>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:44] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.218:4220
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.218:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd150>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:44] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.219:4220
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.219:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdccc50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:44] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.220:4220
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.220:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043250>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:44] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.57:8152
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.57:8152 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042650>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:44] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.54:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.54:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043750>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:44] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.56:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.56:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041f50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:47] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.188:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.188:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041950>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:47] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.163:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.163:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041750>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:47] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.221:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.221:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043b50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:47] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.96:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.96:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042250>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:47] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.154:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.154:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043c50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:47] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.187:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.187:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043950>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:47] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.58:8156
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.58:8156 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcdd50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:47] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.165:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.165:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd450>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:47] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.164:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.164:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc450>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:47] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.94:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.94:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc550>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:50] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.92:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.92:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc850>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:50] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.91:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.91:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc050>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:50] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.93:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.93:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041750>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:50] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.74:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.74:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043750>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:50] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.195:9024
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.195:9024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042b50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:50] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.194:9020
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.194:9020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043350>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:50] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.68:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.68:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042050>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:50] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.67:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.67:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043e50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:50] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.90:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.90:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042750>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:50] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.196:9012
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.196:9012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040f50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:53] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.69:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.69:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040c50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:53] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.199:9000
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.199:9000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043850>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:53] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.80:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.80:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc650>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:53] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.51:9252
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.51:9252 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc250>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:53] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.147:9268
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.147:9268 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc150>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:53] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.71:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.71:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc750>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:53] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.75:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.75:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd250>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:53] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.76:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.76:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcda50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:53] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.85:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.85:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043e50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:53] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.77:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.77:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042b50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:56] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.83:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.83:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041550>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:56] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.81:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.81:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042850>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:56] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.52:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.52:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90040950>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:56] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.78:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.78:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042a50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:56] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.193:8012
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.193:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041150>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:56] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.79:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.79:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041c50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:56] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.87:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.87:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042650>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:56] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.86:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.86:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041950>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:56] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.73:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.73:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc950>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:56] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.72:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.72:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc350>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:59] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.89:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.89:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcce50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:59] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.82:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.82:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdce050>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:59] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.70:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.70:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc550>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:59] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.84:4120
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.84:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a8fdcdd50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:59] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.125:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.125:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90042a50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:59] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.126:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.126:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041550>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:59] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.127:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.127:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90041f50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:39:59] ❌ 测速失败: http://114.241.221.19:4022/rtp/239.3.1.128:8001
   错误: HTTPConnectionPool(host='114.241.221.19', port=4022): Max retries exceeded with url: /rtp/239.3.1.128:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7a90043c50>, 'Connection to 114.241.221.19 timed out. (connect timeout=3.05)')) | 域名: 114.241.221.19
[2025-09-09 09:40:04] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.242:8000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:05] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.117:8000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:05] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.115:8000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:06] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.159:8000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. | 域名: 114.254.39.147
[2025-09-09 09:40:06] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.241:8000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. | 域名: 114.254.39.147
[2025-09-09 09:40:06] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.189:8000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. | 域名: 114.254.39.147
[2025-09-09 09:40:06] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.158:8000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. | 域名: 114.254.39.147
[2025-09-09 09:40:06] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.235:8000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. | 域名: 114.254.39.147
[2025-09-09 09:40:06] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.243:8000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. | 域名: 114.254.39.147
[2025-09-09 09:40:06] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.116:8000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. | 域名: 114.254.39.147
[2025-09-09 09:40:10] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.129:8008
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:10] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.172:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:10] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.60:8084
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:11] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.105:8092
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:11] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.173:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:12] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.130:8004
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:12] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.174:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:12] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.61:8104
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:12] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.175:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:12] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.62:8112
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:15] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.63:8116
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:15] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.152:8120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:15] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.64:8124
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:16] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.124:8128
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:16] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.65:8132
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:17] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.184:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:17] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.153:8136
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:17] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.132:8012
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:17] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.136:8032
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:18] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.151:8144
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:20] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.137:8036
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:20] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.134:8020
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:20] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.135:8028
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:22] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.211:8064
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:22] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.142:8048
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:22] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.141:1234
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:22] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.122:8160
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:22] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.209:8052
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:22] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.148:8072
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:23] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.210:8056
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Read timed out. (read timeout=5) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.240:8172
   错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.26:8108
   错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.156:8148
   错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.46:8124
   错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.123:8164
   错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.133:8016
   错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.45:8304
   错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.149:8076
   错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.138:8044
   错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.29:8288
   错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.42:8172
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.42:8172 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043e50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.47:8164
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.47:8164 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043950>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.39:8300
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.39:8300 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042650>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.27:8128
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.27:8128 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.48:8160
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.48:8160 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.44:8184
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.44:8184 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040e50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.155:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.155:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.49:8188
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.49:8188 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043d50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.43:8176
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.43:8176 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:24] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.41:8140
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.41:8140 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.143:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.143:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.144:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.144:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.236:2000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.236:2000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042e50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.249:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.249:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.238:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.238:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.95:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.95:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.250:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.250:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.100:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.100:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.102:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.102:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc050>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.213:4220
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.213:4220 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.214:4220
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.214:4220 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.216:4220
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.216:4220 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.215:4220
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.215:4220 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.219:4220
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.219:4220 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.218:4220
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.218:4220 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.217:4220
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.217:4220 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdccc50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.56:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.56:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.57:8152
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.57:8152 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.54:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.54:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.220:4220
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.220:4220 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.188:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.188:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041e50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.221:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.221:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042d50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.163:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.163:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.154:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.154:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.58:8156
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.58:8156 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.96:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.96:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.164:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.164:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcda50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.165:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.165:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.94:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.94:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.187:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.187:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdccd50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.92:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.92:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.91:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.91:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.194:9020
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.194:9020 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.74:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.74:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043950>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.195:9024
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.195:9024 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.93:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.93:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042050>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.67:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.67:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043d50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.90:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.90:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.196:9012
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.196:9012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.68:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.68:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.69:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.69:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdccb50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.51:9252
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.51:9252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.199:9000
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.199:9000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcce50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.80:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.80:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcca50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.147:9268
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.147:9268 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc050>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.71:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.71:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcde50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.75:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.75:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042050>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.77:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.77:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.76:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.76:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:25] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.85:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.85:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.81:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.81:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.83:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.83:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040e50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.52:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.52:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.78:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.78:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.87:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.87:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc950>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.72:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.72:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdccd50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.73:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.73:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcdd50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.193:8012
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.193:8012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdce150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.79:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.79:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.86:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.86:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdce050>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.82:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.82:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcdc50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.70:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.70:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040e50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.89:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.89:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.125:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.125:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.127:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.127:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.126:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.126:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.128:8001
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.128:8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:26] ❌ 测速失败: http://114.254.39.147:8888/rtp/239.3.1.84:4120
   错误: HTTPConnectionPool(host='114.254.39.147', port=8888): Max retries exceeded with url: /rtp/239.3.1.84:4120 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 114.254.39.147
[2025-09-09 09:40:29] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.129:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.24s
[2025-09-09 09:40:29] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.149:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.25s
[2025-09-09 09:40:29] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.123:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.24s
[2025-09-09 09:40:29] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.151:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.24s
[2025-09-09 09:40:32] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.128:5002
   速度: 909.72KB/s | 数据量: 5120.0KB | 总耗时: 6.14s
[2025-09-09 09:40:32] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.133:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:32] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.131:5002
   速度: 875.23KB/s | 数据量: 5120.0KB | 总耗时: 6.34s
[2025-09-09 09:40:32] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.130:5002
   速度: 842.18KB/s | 数据量: 5120.0KB | 总耗时: 6.57s
[2025-09-09 09:40:32] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.122:5002
   速度: 1031.74KB/s | 数据量: 6144.0KB | 总耗时: 6.44s
[2025-09-09 09:40:32] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.111:5002
   速度: 832.28KB/s | 数据量: 5120.0KB | 总耗时: 6.64s
[2025-09-09 09:40:32] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.120:5002
   速度: 842.57KB/s | 数据量: 5120.0KB | 总耗时: 6.61s
[2025-09-09 09:40:33] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.160:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.60s
[2025-09-09 09:40:35] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.196:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.86s
[2025-09-09 09:40:35] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.119:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.80s
[2025-09-09 09:40:35] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.192:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.63s
[2025-09-09 09:40:35] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.195:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:35] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.138:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.91s
[2025-09-09 09:40:35] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.140:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.81s
[2025-09-09 09:40:35] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.121:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.11s
[2025-09-09 09:40:37] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.158:5002
   速度: 156.86KB/s | 数据量: 1024.0KB | 总耗时: 7.63s
[2025-09-09 09:40:37] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.150:5002
   速度: 863.90KB/s | 数据量: 5120.0KB | 总耗时: 8.08s
[2025-09-09 09:40:38] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.194:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:38] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.215:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-09 09:40:38] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.144:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:39] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.142:5002
   速度: 1123.44KB/s | 数据量: 6144.0KB | 总耗时: 6.02s
[2025-09-09 09:40:40] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.213:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.36s
[2025-09-09 09:40:40] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.175:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.91s
[2025-09-09 09:40:41] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.52:5002
   速度: 1128.90KB/s | 数据量: 6144.0KB | 总耗时: 5.92s
[2025-09-09 09:40:41] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.193:5002
   速度: 1130.33KB/s | 数据量: 6144.0KB | 总耗时: 5.93s
[2025-09-09 09:40:41] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.237:5002
   速度: 1129.83KB/s | 数据量: 6144.0KB | 总耗时: 5.94s
[2025-09-09 09:40:41] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.176:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:41] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.173:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:41] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.214:5002
   速度: 1128.03KB/s | 数据量: 6144.0KB | 总耗时: 5.99s
[2025-09-09 09:40:43] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.169:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:43] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.172:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:44] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.174:5002
   速度: 1132.13KB/s | 数据量: 6144.0KB | 总耗时: 5.96s
[2025-09-09 09:40:44] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.170:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:44] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.127:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:44] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.166:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.08s
[2025-09-09 09:40:44] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.177:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.06s
[2025-09-09 09:40:44] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.171:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.08s
[2025-09-09 09:40:44] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.167:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:45] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.168:5002
   速度: 1127.54KB/s | 数据量: 6144.0KB | 总耗时: 5.99s
[2025-09-09 09:40:47] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.81:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:47] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.26:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-09 09:40:47] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.114:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:47] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.147:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:47] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.116:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-09 09:40:49] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.112:5002
   速度: 1136.87KB/s | 数据量: 6144.0KB | 总耗时: 5.92s
[2025-09-09 09:40:49] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.113:5002
   速度: 1129.14KB/s | 数据量: 6144.0KB | 总耗时: 5.99s
[2025-09-09 09:40:50] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.31:5002
   速度: 1125.25KB/s | 数据量: 6144.0KB | 总耗时: 5.95s
[2025-09-09 09:40:50] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.126:5002
   速度: 1129.24KB/s | 数据量: 6144.0KB | 总耗时: 5.94s
[2025-09-09 09:40:50] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.154:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:50] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.155:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:50] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.28:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:50] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.117:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:51] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.123:5002
   速度: 1130.68KB/s | 数据量: 6144.0KB | 总耗时: 5.98s
[2025-09-09 09:40:52] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.27:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:52] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.82:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.08s
[2025-09-09 09:40:53] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.29:5002
   速度: 1125.44KB/s | 数据量: 6144.0KB | 总耗时: 6.00s
[2025-09-09 09:40:53] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.32:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:53] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.54:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-09 09:40:53] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.56:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:53] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.50:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:56] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.115:5002
   速度: 1129.35KB/s | 数据量: 6144.0KB | 总耗时: 5.97s
[2025-09-09 09:40:56] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.61:5002
   速度: 1126.45KB/s | 数据量: 6144.0KB | 总耗时: 6.01s
[2025-09-09 09:40:56] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.51:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:56] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.57:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:56] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.118:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:56] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.181:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:56] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.35:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-09 09:40:58] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.41:5002
   速度: 328.67KB/s | 数据量: 2048.0KB | 总耗时: 6.88s
[2025-09-09 09:40:59] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.30:5002
   速度: 330.60KB/s | 数据量: 2048.0KB | 总耗时: 6.80s
[2025-09-09 09:40:59] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.61:5002
   速度: 327.98KB/s | 数据量: 2048.0KB | 总耗时: 6.89s
[2025-09-09 09:40:59] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.141:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:59] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.19:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:59] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.236:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.08s
[2025-09-09 09:40:59] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.139:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:59] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.146:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:40:59] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.134:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:02] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.124:5002
   速度: 1132.61KB/s | 数据量: 6144.0KB | 总耗时: 5.97s
[2025-09-09 09:41:02] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.236:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-09 09:41:02] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.129:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-09 09:41:02] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.104:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-09 09:41:02] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.105:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:02] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.145:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:02] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.247:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:03] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.237:5002
   速度: 1129.34KB/s | 数据量: 6144.0KB | 总耗时: 5.95s
[2025-09-09 09:41:05] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.143:5002
   速度: 1116.89KB/s | 数据量: 6144.0KB | 总耗时: 6.02s
[2025-09-09 09:41:05] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.135:5002
   速度: 1135.97KB/s | 数据量: 6144.0KB | 总耗时: 6.01s
[2025-09-09 09:41:05] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.207:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:05] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.55:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:05] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.110:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:05] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.82:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:05] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.137:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-09 09:41:08] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.57:5002
   速度: 1132.39KB/s | 数据量: 6144.0KB | 总耗时: 6.02s
[2025-09-09 09:41:08] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.14:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:08] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.58:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:08] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.7:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.10s
[2025-09-09 09:41:08] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.83:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:08] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.8:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-09 09:41:08] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.62:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:09] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.27:5002
   速度: 330.55KB/s | 数据量: 2048.0KB | 总耗时: 6.82s
[2025-09-09 09:41:11] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.2:5002
   速度: 306.12KB/s | 数据量: 2048.0KB | 总耗时: 7.31s
[2025-09-09 09:41:11] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.173:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-09 09:41:11] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.172:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:11] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.205:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:11] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.175:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:11] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.174:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:12] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.179:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 1.00s
[2025-09-09 09:41:12] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.2.4:5002
   速度: 305.20KB/s | 数据量: 2048.0KB | 总耗时: 7.33s
[2025-09-09 09:41:12] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.124:6108
   速度: 391.84KB/s | 数据量: 313.6KB | 总耗时: 1.19s
[2025-09-09 09:41:12] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.60:6108
   速度: 419.57KB/s | 数据量: 336.7KB | 总耗时: 1.19s
[2025-09-09 09:41:13] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.125:6108
   速度: 494.46KB/s | 数据量: 489.9KB | 总耗时: 1.38s
[2025-09-09 09:41:14] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.126:6108
   速度: 495.69KB/s | 数据量: 489.9KB | 总耗时: 1.38s
[2025-09-09 09:41:14] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.204:6108
   速度: 462.74KB/s | 数据量: 459.2KB | 总耗时: 1.39s
[2025-09-09 09:41:14] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.127:6108
   速度: 478.74KB/s | 数据量: 482.9KB | 总耗时: 1.40s
[2025-09-09 09:41:14] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.180:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-09 09:41:14] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.178:5002
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-09 09:41:15] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.171:5002
   速度: 329.45KB/s | 数据量: 2048.0KB | 总耗时: 6.82s
[2025-09-09 09:41:15] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.206:6108
   速度: 608.51KB/s | 数据量: 692.7KB | 总耗时: 1.53s
[2025-09-09 09:41:15] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.2:6108
   速度: 641.52KB/s | 数据量: 681.1KB | 总耗时: 1.45s
[2025-09-09 09:41:15] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.1:6108
   速度: 643.55KB/s | 数据量: 691.4KB | 总耗时: 1.47s
[2025-09-09 09:41:15] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.205:6108
   速度: 717.02KB/s | 数据量: 922.7KB | 总耗时: 1.68s
[2025-09-09 09:41:15] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.216:5002
   速度: 310.81KB/s | 数据量: 2048.0KB | 总耗时: 7.21s
[2025-09-09 09:41:15] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.143:7143
   速度: 478.15KB/s | 数据量: 471.8KB | 总耗时: 1.38s
[2025-09-09 09:41:15] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.156:7156
   速度: 479.19KB/s | 数据量: 480.1KB | 总耗时: 1.40s
[2025-09-09 09:41:16] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.176:5002
   速度: 330.87KB/s | 数据量: 2048.0KB | 总耗时: 6.81s
[2025-09-09 09:41:16] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.112:6108
   速度: 491.88KB/s | 数据量: 489.9KB | 总耗时: 1.39s
[2025-09-09 09:41:16] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.157:7157
   速度: 389.52KB/s | 数据量: 304.6KB | 总耗时: 1.17s
[2025-09-09 09:41:16] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.158:7158
   速度: 377.52KB/s | 数据量: 302.0KB | 总耗时: 1.20s
[2025-09-09 09:41:16] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.7:6108
   速度: 385.45KB/s | 数据量: 313.6KB | 总耗时: 1.21s
[2025-09-09 09:41:16] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.17:6108
   速度: 398.14KB/s | 数据量: 323.9KB | 总耗时: 1.21s
[2025-09-09 09:41:16] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.9:6108
   速度: 332.90KB/s | 数据量: 262.2KB | 总耗时: 1.17s
[2025-09-09 09:41:17] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.242:6108
   速度: 493.89KB/s | 数据量: 481.5KB | 总耗时: 1.36s
[2025-09-09 09:41:17] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.10:6108
   速度: 476.85KB/s | 数据量: 471.8KB | 总耗时: 1.39s
[2025-09-09 09:41:17] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.15:6108
   速度: 94.57KB/s | 数据量: 20.6KB | 总耗时: 0.62s
[2025-09-09 09:41:17] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.211:6108
   速度: 83.09KB/s | 数据量: 19.3KB | 总耗时: 0.62s
[2025-09-09 09:41:17] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.12:6108
   速度: 486.05KB/s | 数据量: 477.3KB | 总耗时: 1.37s
[2025-09-09 09:41:17] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.249:6108
   速度: 164.46KB/s | 数据量: 65.5KB | 总耗时: 0.78s
[2025-09-09 09:41:17] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.161:7161
   速度: 155.42KB/s | 数据量: 63.0KB | 总耗时: 0.79s
[2025-09-09 09:41:17] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.202:6108
   速度: 207.31KB/s | 数据量: 124.7KB | 总耗时: 1.00s
[2025-09-09 09:41:17] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.14:6108
   速度: 194.61KB/s | 数据量: 115.7KB | 总耗时: 0.98s
[2025-09-09 09:41:18] ✅ 测速成功: http://111.162.206.15:8686/rtp/225.1.1.177:5002
   速度: 330.00KB/s | 数据量: 2048.0KB | 总耗时: 6.81s
[2025-09-09 09:41:19] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.63:6108
   速度: 645.67KB/s | 数据量: 700.4KB | 总耗时: 1.48s
[2025-09-09 09:41:19] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.212:6108
   速度: 761.65KB/s | 数据量: 1430.4KB | 总耗时: 2.27s
[2025-09-09 09:41:19] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.64:6108
   速度: 747.20KB/s | 数据量: 1074.4KB | 总耗时: 1.83s
[2025-09-09 09:41:19] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.65:6108
   速度: 790.92KB/s | 数据量: 1256.9KB | 总耗时: 1.97s
[2025-09-09 09:41:19] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.237:6108
   速度: 740.01KB/s | 数据量: 1218.3KB | 总耗时: 2.03s
[2025-09-09 09:41:19] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.62:6108
   速度: 738.04KB/s | 数据量: 1055.1KB | 总耗时: 1.83s
[2025-09-09 09:41:19] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.235:6108
   速度: 741.41KB/s | 数据量: 1316.0KB | 总耗时: 2.16s
[2025-09-09 09:41:19] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.236:6108
   速度: 730.19KB/s | 数据量: 1265.9KB | 总耗时: 2.13s
[2025-09-09 09:41:19] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.61:6108
   速度: 763.43KB/s | 数据量: 1211.9KB | 总耗时: 1.99s
[2025-09-09 09:41:19] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.233:6108
   速度: 705.82KB/s | 数据量: 1319.9KB | 总耗时: 2.27s
[2025-09-09 09:41:20] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.122:6108
   速度: 493.62KB/s | 数据量: 422.8KB | 总耗时: 1.26s
[2025-09-09 09:41:20] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.120:6108
   速度: 471.94KB/s | 数据量: 454.9KB | 总耗时: 1.35s
[2025-09-09 09:41:20] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.159:7159
   速度: 459.89KB/s | 数据量: 444.7KB | 总耗时: 1.35s
[2025-09-09 09:41:20] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.144:7144
   速度: 467.82KB/s | 数据量: 453.7KB | 总耗时: 1.36s
[2025-09-09 09:41:20] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.67:6108
   速度: 475.32KB/s | 数据量: 463.9KB | 总耗时: 1.37s
[2025-09-09 09:41:20] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.147:7147
   速度: 457.49KB/s | 数据量: 445.9KB | 总耗时: 1.37s
[2025-09-09 09:41:20] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.160:7160
   速度: 460.15KB/s | 数据量: 448.5KB | 总耗时: 1.37s
[2025-09-09 09:41:20] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.123:6108
   速度: 434.86KB/s | 数据量: 431.8KB | 总耗时: 1.39s
[2025-09-09 09:41:20] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.66:6108
   速度: 452.05KB/s | 数据量: 457.5KB | 总耗时: 1.42s
[2025-09-09 09:41:21] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.121:6108
   速度: 439.11KB/s | 数据量: 445.9KB | 总耗时: 1.42s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.45:6108
   速度: 819.03KB/s | 数据量: 1435.5KB | 总耗时: 2.13s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.68:6108
   速度: 811.78KB/s | 数据量: 1385.4KB | 总耗时: 2.09s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.57:6108
   速度: 783.43KB/s | 数据量: 1376.4KB | 总耗时: 2.16s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.168:7168
   速度: 786.02KB/s | 数据量: 1450.9KB | 总耗时: 2.25s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.230:6108
   速度: 785.97KB/s | 数据量: 1368.7KB | 总耗时: 2.14s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.54:6108
   速度: 799.75KB/s | 数据量: 1381.5KB | 总耗时: 2.11s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.165:7165
   速度: 743.06KB/s | 数据量: 1304.4KB | 总耗时: 2.15s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.47:6108
   速度: 316.41KB/s | 数据量: 533.3KB | 总耗时: 2.09s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.37:6108
   速度: 751.63KB/s | 数据量: 1317.3KB | 总耗时: 2.15s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.231:6108
   速度: 743.22KB/s | 数据量: 1303.1KB | 总耗时: 2.14s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.56:6108
   速度: 56.26KB/s | 数据量: 1.3KB | 总耗时: 0.41s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.174:7174
   速度: 38.01KB/s | 数据量: 1.3KB | 总耗时: 0.41s
[2025-09-09 09:41:23] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.48:6108
   速度: 34.80KB/s | 数据量: 1.3KB | 总耗时: 0.42s
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.59:6108
   速度: 273.30KB/s | 数据量: 168.4KB | 总耗时: 1.00s
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.30:6108
   速度: 307.61KB/s | 数据量: 195.3KB | 总耗时: 1.03s
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.51:6108
   速度: 306.68KB/s | 数据量: 196.6KB | 总耗时: 1.04s
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.53:6108
   速度: 269.57KB/s | 数据量: 176.1KB | 总耗时: 1.04s
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.52:6108
   速度: 252.72KB/s | 数据量: 165.8KB | 总耗时: 1.05s
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.241:6108
   速度: 71.62KB/s | 数据量: 21.8KB | 总耗时: 0.69s
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.126:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.126:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043950>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.145:7145
   速度: 478.42KB/s | 数据量: 482.9KB | 总耗时: 1.40s
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.234:6108
   速度: 246.55KB/s | 数据量: 156.8KB | 总耗时: 1.03s
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.203:6108
   速度: 467.74KB/s | 数据量: 485.7KB | 总耗时: 1.44s
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.146:7146
   速度: 198.27KB/s | 数据量: 127.2KB | 总耗时: 1.03s
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.154:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.154:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.25:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.25:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.164:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.164:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.150:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.150:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.241:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.241:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.151:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.151:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.86:6108
   速度: 88.32KB/s | 数据量: 27.0KB | 总耗时: 0.71s
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.168:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.168:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.156:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.156:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042d50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:24] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.198:7198
   速度: 154.53KB/s | 数据量: 73.3KB | 总耗时: 0.87s
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.165:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.165:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:24] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.27:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.27:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.177:7177
   速度: 165.56KB/s | 数据量: 79.7KB | 总耗时: 0.89s
[2025-09-09 09:41:25] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.240:6108
   速度: 114.00KB/s | 数据量: 56.5KB | 总耗时: 0.89s
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.170:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.170:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.135:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.135:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdce650>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.201:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.201:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.171:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.171:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdccb50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.93:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.93:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.172:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.172:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcde50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.136:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.136:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.173:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.173:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.137:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.137:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.138:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.138:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.178:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.178:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcdc50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.139:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.139:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdce150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ✅ 测速成功: http://113.56.95.223:8889/rtp/228.0.0.16:6108
   速度: 304.16KB/s | 数据量: 255.7KB | 总耗时: 1.24s
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.15:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.15:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.140:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.140:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042d50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.182:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.182:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.179:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.179:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.230:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.230:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.29:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.29:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.45:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.45:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043950>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.38:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.38:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.52:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.52:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdccb50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.47:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.47:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040e50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.60:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.60:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.56:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.56:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdce650>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.58:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.58:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcca50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.63:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.63:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.51:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.51:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.206:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.206:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdccc50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.117:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.117:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd650>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.125:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.125:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.122:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.122:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.123:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.123:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042d50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.116:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.116:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.141:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.141:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.115:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.115:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043e50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.181:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.181:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.131:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.131:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.130:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.130:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.124:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.124:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.185:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.185:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:25] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.186:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.186:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.74:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.74:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdce350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.110:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.110:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdce050>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.26:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.26:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdccd50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.95:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.95:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.82:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.82:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd050>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.49:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.49:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.80:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.80:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.101:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.101:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.40:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.40:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.35:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.35:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.111:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.111:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.34:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.34:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.180:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.180:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.76:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.76:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.86:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.86:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.18:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.18:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.50:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.50:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.114:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.114:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.160:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.160:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcdd50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.212:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.212:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.238:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.238:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.169:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.169:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.239:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.239:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.67:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.67:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041950>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.161:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.161:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.163:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.163:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043d50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.90:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.90:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.162:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.162:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040950>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.98:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.98:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.107:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.107:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.108:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.108:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.127:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.127:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.128:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.128:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcce50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.133:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.133:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.134:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.134:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcde50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.149:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.149:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdccd50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.53:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.53:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.188:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.188:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041950>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.59:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.59:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.198:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.198:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.28:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.28:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042d50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.6:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.6:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.43:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.43:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042650>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.8:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.8:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.103:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.103:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.159:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.159:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041750>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:26] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.157:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.157:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.104:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.104:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdce350>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.57:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.57:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90041b50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.105:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.105:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd050>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.109:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.109:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcda50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.102:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.102:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcc150>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.213:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.213:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a8fdcd650>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.148:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.148:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042650>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.118:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.118:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043c50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.119:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.119:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90040f50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.187:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.187:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042450>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.203:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.203:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042e50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.197:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.197:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042850>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.48:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.48:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.155:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.155:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90043250>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.214:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.214:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042a50>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ❌ 测速失败: http://116.2.162.16:4010/rtp/232.0.0.215:1234
   错误: HTTPConnectionPool(host='116.2.162.16', port=4010): Max retries exceeded with url: /rtp/232.0.0.215:1234 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a90042550>: Failed to establish a new connection: [Errno 111] Connection refused')) | 域名: 116.2.162.16
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.42s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0003_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0003_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0003_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0003_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0004_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0004_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:27] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0004_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0006_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0006_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0006_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0008_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0008_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 418.95KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/1005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0009_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 397.46KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0009_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 397.46KB/s | 数据量: 0.4KB | 总耗时: 0.42s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0010_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0010_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0010_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0011_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0011_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0011_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0011_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.42s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0012_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:28] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0012_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0013_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0012_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0013_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0013_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0014_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 423.83KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0014_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0014_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0014_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 423.83KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0015_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0015_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0015_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 402.34KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0015_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 413.09KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0107_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0107_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0122_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0122_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0130_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0130_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0127_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0127_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/0139_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 407.23KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:29] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/0139_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 407.23KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0139_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0139_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0124_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0124_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/0128_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/0128_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 417.97KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/1014_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1014_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1012_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/1008_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/1008_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/1011_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1011_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/1008_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1008_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/1009_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1009_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/1010_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1010_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/1007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/1010_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/1017_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/1010_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1017_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/1007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/1009_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.42s
[2025-09-09 09:41:30] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/1007_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.42s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1013_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/1009_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/1013_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/1006_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/1006_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/1002_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/1002_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/1005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/1005_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.234.2:9901/tsfile/live/1016_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.41s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.235.177:9901/tsfile/live/1016_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 422.85KB/s | 数据量: 0.4KB | 总耗时: 0.40s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.234.102:9901/tsfile/live/1001_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.39s
[2025-09-09 09:41:31] ✅ 测速成功: http://221.13.235.227:9901/tsfile/live/1001_1.m3u8?key=txiptv&playlive=1&authid=0
   速度: 412.11KB/s | 数据量: 0.4KB | 总耗时: 0.41s
